package vast_versions

import (
	version_4_6_0 "github.com/vast-data/terraform-provider-vastdata/codegen/4.6.0"
	version_4_7_0 "github.com/vast-data/terraform-provider-vastdata/codegen/4.7.0"
	"reflect"
)

var vast_versions map[string]map[string]reflect.Type = map[string]map[string]reflect.Type{
	"4.6.0": map[string]reflect.Type{
		"ActiveDirectory":          reflect.TypeOf((*version_4_6_0.ActiveDirectory)(nil)).Elem(),
		"Cnode":                    reflect.TypeOf((*version_4_6_0.Cnode)(nil)).Elem(),
		"DefaultQuota":             reflect.TypeOf((*version_4_6_0.DefaultQuota)(nil)).Elem(),
		"Dns":                      reflect.TypeOf((*version_4_6_0.Dns)(nil)).Elem(),
		"DnsPost":                  reflect.TypeOf((*version_4_6_0.DnsPost)(nil)).Elem(),
		"GlobalSnapshot":           reflect.TypeOf((*version_4_6_0.GlobalSnapshot)(nil)).Elem(),
		"Group":                    reflect.TypeOf((*version_4_6_0.Group)(nil)).Elem(),
		"GroupPost":                reflect.TypeOf((*version_4_6_0.GroupPost)(nil)).Elem(),
		"Ldap":                     reflect.TypeOf((*version_4_6_0.Ldap)(nil)).Elem(),
		"Nis":                      reflect.TypeOf((*version_4_6_0.Nis)(nil)).Elem(),
		"NisrPost":                 reflect.TypeOf((*version_4_6_0.NisrPost)(nil)).Elem(),
		"ProtectedPath":            reflect.TypeOf((*version_4_6_0.ProtectedPath)(nil)).Elem(),
		"ProtectionPolicy":         reflect.TypeOf((*version_4_6_0.ProtectionPolicy)(nil)).Elem(),
		"ProtectionPolicySchedule": reflect.TypeOf((*version_4_6_0.ProtectionPolicySchedule)(nil)).Elem(),
		"QosDynamicLimits":         reflect.TypeOf((*version_4_6_0.QosDynamicLimits)(nil)).Elem(),
		"QosPolicy":                reflect.TypeOf((*version_4_6_0.QosPolicy)(nil)).Elem(),
		"QosStaticLimits":          reflect.TypeOf((*version_4_6_0.QosStaticLimits)(nil)).Elem(),
		"Quota":                    reflect.TypeOf((*version_4_6_0.Quota)(nil)).Elem(),
		"QuotaEntityInfo":          reflect.TypeOf((*version_4_6_0.QuotaEntityInfo)(nil)).Elem(),
		"ReplicationPeers":         reflect.TypeOf((*version_4_6_0.ReplicationPeers)(nil)).Elem(),
		"S3LifeCycleRule":          reflect.TypeOf((*version_4_6_0.S3LifeCycleRule)(nil)).Elem(),
		"S3Policy":                 reflect.TypeOf((*version_4_6_0.S3Policy)(nil)).Elem(),
		"S3replicationPeers":       reflect.TypeOf((*version_4_6_0.S3replicationPeers)(nil)).Elem(),
		"ShareAcl":                 reflect.TypeOf((*version_4_6_0.ShareAcl)(nil)).Elem(),
		"Snapshot":                 reflect.TypeOf((*version_4_6_0.Snapshot)(nil)).Elem(),
		"Tenant":                   reflect.TypeOf((*version_4_6_0.Tenant)(nil)).Elem(),
		"TenantPost":               reflect.TypeOf((*version_4_6_0.TenantPost)(nil)).Elem(),
		"User":                     reflect.TypeOf((*version_4_6_0.User)(nil)).Elem(),
		"UserPost":                 reflect.TypeOf((*version_4_6_0.UserPost)(nil)).Elem(),
		"UserQuota":                reflect.TypeOf((*version_4_6_0.UserQuota)(nil)).Elem(),
		"View":                     reflect.TypeOf((*version_4_6_0.View)(nil)).Elem(),
		"ViewCreate":               reflect.TypeOf((*version_4_6_0.ViewCreate)(nil)).Elem(),
		"ViewPolicy":               reflect.TypeOf((*version_4_6_0.ViewPolicy)(nil)).Elem(),
		"ViewPolicyPost":           reflect.TypeOf((*version_4_6_0.ViewPolicyPost)(nil)).Elem(),
		"ViewShareAcl":             reflect.TypeOf((*version_4_6_0.ViewShareAcl)(nil)).Elem(),
		"VipPool":                  reflect.TypeOf((*version_4_6_0.VipPool)(nil)).Elem(),
		"VipPoolPost":              reflect.TypeOf((*version_4_6_0.VipPoolPost)(nil)).Elem(),
	},
	"4.7.0": map[string]reflect.Type{
		"ActiveDirectory":          reflect.TypeOf((*version_4_7_0.ActiveDirectory)(nil)).Elem(),
		"Cnode":                    reflect.TypeOf((*version_4_7_0.Cnode)(nil)).Elem(),
		"DefaultQuota":             reflect.TypeOf((*version_4_7_0.DefaultQuota)(nil)).Elem(),
		"Dns":                      reflect.TypeOf((*version_4_7_0.Dns)(nil)).Elem(),
		"DnsPost":                  reflect.TypeOf((*version_4_7_0.DnsPost)(nil)).Elem(),
		"GlobalSnapshot":           reflect.TypeOf((*version_4_7_0.GlobalSnapshot)(nil)).Elem(),
		"Group":                    reflect.TypeOf((*version_4_7_0.Group)(nil)).Elem(),
		"GroupPost":                reflect.TypeOf((*version_4_7_0.GroupPost)(nil)).Elem(),
		"Ldap":                     reflect.TypeOf((*version_4_7_0.Ldap)(nil)).Elem(),
		"Nis":                      reflect.TypeOf((*version_4_7_0.Nis)(nil)).Elem(),
		"NisrPost":                 reflect.TypeOf((*version_4_7_0.NisrPost)(nil)).Elem(),
		"ProtectedPath":            reflect.TypeOf((*version_4_7_0.ProtectedPath)(nil)).Elem(),
		"ProtectionPolicy":         reflect.TypeOf((*version_4_7_0.ProtectionPolicy)(nil)).Elem(),
		"ProtectionPolicySchedule": reflect.TypeOf((*version_4_7_0.ProtectionPolicySchedule)(nil)).Elem(),
		"QosDynamicLimits":         reflect.TypeOf((*version_4_7_0.QosDynamicLimits)(nil)).Elem(),
		"QosPolicy":                reflect.TypeOf((*version_4_7_0.QosPolicy)(nil)).Elem(),
		"QosStaticLimits":          reflect.TypeOf((*version_4_7_0.QosStaticLimits)(nil)).Elem(),
		"Quota":                    reflect.TypeOf((*version_4_7_0.Quota)(nil)).Elem(),
		"QuotaEntityInfo":          reflect.TypeOf((*version_4_7_0.QuotaEntityInfo)(nil)).Elem(),
		"ReplicationPeers":         reflect.TypeOf((*version_4_7_0.ReplicationPeers)(nil)).Elem(),
		"S3LifeCycleRule":          reflect.TypeOf((*version_4_7_0.S3LifeCycleRule)(nil)).Elem(),
		"S3Policy":                 reflect.TypeOf((*version_4_7_0.S3Policy)(nil)).Elem(),
		"S3replicationPeers":       reflect.TypeOf((*version_4_7_0.S3replicationPeers)(nil)).Elem(),
		"ShareAcl":                 reflect.TypeOf((*version_4_7_0.ShareAcl)(nil)).Elem(),
		"Snapshot":                 reflect.TypeOf((*version_4_7_0.Snapshot)(nil)).Elem(),
		"Tenant":                   reflect.TypeOf((*version_4_7_0.Tenant)(nil)).Elem(),
		"TenantPost":               reflect.TypeOf((*version_4_7_0.TenantPost)(nil)).Elem(),
		"User":                     reflect.TypeOf((*version_4_7_0.User)(nil)).Elem(),
		"UserPost":                 reflect.TypeOf((*version_4_7_0.UserPost)(nil)).Elem(),
		"UserQuota":                reflect.TypeOf((*version_4_7_0.UserQuota)(nil)).Elem(),
		"View":                     reflect.TypeOf((*version_4_7_0.View)(nil)).Elem(),
		"ViewCreate":               reflect.TypeOf((*version_4_7_0.ViewCreate)(nil)).Elem(),
		"ViewPolicy":               reflect.TypeOf((*version_4_7_0.ViewPolicy)(nil)).Elem(),
		"ViewPolicyPost":           reflect.TypeOf((*version_4_7_0.ViewPolicyPost)(nil)).Elem(),
		"ViewShareAcl":             reflect.TypeOf((*version_4_7_0.ViewShareAcl)(nil)).Elem(),
		"VipPool":                  reflect.TypeOf((*version_4_7_0.VipPool)(nil)).Elem(),
		"VipPoolPost":              reflect.TypeOf((*version_4_7_0.VipPoolPost)(nil)).Elem(),
	},
}
