/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DefaultQuota struct {
	// The system ID of the quota
	QuotaSystemId int32 `json:"quota_system_id,omitempty"`
	// The size soft limit in bytes
	SoftLimit int64 `json:"soft_limit,omitempty"`
	// The size hard limit in bytes
	HardLimit int64 `json:"hard_limit,omitempty"`
	// The sof limit of inodes number
	SofLimitInodes int64 `json:"sof_limit_inodes,omitempty"`
	// The hard limit in inode number
	HardLimitInodes int64 `json:"hard_limit_inodes,omitempty"`
	GracePeriod string `json:"grace_period,omitempty"`
}
