/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ActiveDirectory struct {
	Id int32 `json:"id,omitempty"`
	// GUID
	Guid string `json:"guid,omitempty"`
	// The domain name of the AD
	DomainName string `json:"domain_name,omitempty"`
	// Name of the computer object/machine account to add. Recommended to be the name of the cluster.
	MachineAccountName string `json:"machine_account_name,omitempty"`
	// List of Domain Controllers to prefer for authentication. DCs listed here will be queried exclusively unless they fail or do not respond. In such a case, other DCs will be consulted. Specify as a comma-separated list. Each entry can be a fully-qualified hostname or an IP address.
	PreferredDcList []string `json:"preferred_dc_list,omitempty"`
	// Organizational Unit within AD where the Cluster Machine account will be created. If left empty, it will go into default Computers OU
	OrganizationalUnit string `json:"organizational_unit,omitempty"`
	IsVmsAuthProvider bool `json:"is_vms_auth_provider,omitempty"`
	// the id of the attached LDAP object
	LdapId string `json:"ldap_id,omitempty"`
	// enabled/disabled
	Enabled bool `json:"enabled,omitempty"`
	MatchUser string `json:"match_user,omitempty"`
	Method string `json:"method,omitempty"`
	Port int `json:"port,omitempty"`
	PosixAccount string `json:"posix_account,omitempty"`
	PosixGroup string `json:"posix_group,omitempty"`
	QueryGroupsMode string `json:"query_groups_mode,omitempty"`
	QueryPosixAttributesFromGc bool `json:"query_posix_attributes_from_gc,omitempty"`
	SmbAllowed bool `json:"smb_allowed,omitempty"`
	Uid string `json:"uid,omitempty"`
	UidMember string `json:"uid_member,omitempty"`
	UidMemberValuePropertyName string `json:"uid_member_value_property_name,omitempty"`
	// Use auto dicovery with to obtain AD details
	UseAutoDiscovery bool `json:"use_auto_discovery,omitempty"`
	UseLdaps bool `json:"use_ldaps,omitempty"`
	UseTls bool `json:"use_tls,omitempty"`
	UserLoginName string `json:"user_login_name,omitempty"`
	UsernamePropertyName string `json:"username_property_name,omitempty"`
	// Active Directory state
	State string `json:"state,omitempty"`
}
