/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GlobalSnapshot struct {
	// A unique id given to the global snapshot
	Id int64 `json:"id,omitempty"`
	// A unique guid given to the global snapshot
	Guid string `json:"guid,omitempty"`
	// The name of the snapshot
	Name string `json:"name,omitempty"`
	// The path to make snapshot from
	SourcePath string `json:"source_path,omitempty"`
	// The tenant id to use
	TenantId int `json:"tenant_id,omitempty"`
	// The path where to store the snapshot on a Target
	LoaneeRootPath string `json:"loanee_root_path,omitempty"`
	// The remote tenant id
	RemoteTargetId int `json:"remote_target_id,omitempty"`
	// The snapshot id of the snapshot
	LoaneeSnapshotId int `json:"loanee_snapshot_id,omitempty"`
	// The name of the snapshot
	LoaneeSnapsho string `json:"loanee_snapsho,omitempty"`
	// IS the snapshot enabled
	Enabled bool `json:"enabled,omitempty"`
	// The cluster where the source snapshot is configured
	SourceCluster string `json:"source_cluster,omitempty"`
	// The cluster where the snapshot is cloned to
	TargetCluster string `json:"target_cluster,omitempty"`
}
