/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type S3replicationPeers struct {
	// A unique id given to the s3 replication peer configuration
	Id int64 `json:"id,omitempty"`
	// A unique guid given to the s3 replication peer configuration
	Guid string `json:"guid,omitempty"`
	// The name of the s3 replication peer configuration
	Name string `json:"name,omitempty"`
	// Direct link to the s3 replication peer configurations
	Url string `json:"url,omitempty"`
	// The name of the peer bucket to replicate to
	BucketName string `json:"bucket_name,omitempty"`
	// The http protocol user http/https
	HttpProtocol string `json:"http_protocol,omitempty"`
	// The type of the peer bucket CUSTOM_S3/AWS_S3
	Type_ string `json:"type"`
	// List of http procies
	Proxies []string `json:"proxies,omitempty"`
	// The Bucket AWS region, Valid only when type is AWS_S3
	AwsRegion string `json:"aws_region,omitempty"`
	// The S3 access key
	AccessKey string `json:"access_key,omitempty"`
	// The S3 secret key
	SecretKey string `json:"secret_key,omitempty"`
	// The S3 url of the bucket (dns name/ip) used only when using CUSTOM_S3
	CustomBucketUrl string `json:"custom_bucket_url,omitempty"`
}
