/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VipPool struct {
	// The unique ID of the virtual IP pool.
	Id int32 `json:"id,omitempty"`
	// The unique GUID of the virtual IP pool.
	Guid string `json:"guid,omitempty"`
	// The unique name of the virtual IP pool.
	Name string `json:"name,omitempty"`
	// IPv4 subnet CIDR prefix (number of bits).
	SubnetCidr int32 `json:"subnet_cidr,omitempty"`
	// IPv6 subnet CIDR prefix (number of bits).
	SubnetCidrIpv6 int32 `json:"subnet_cidr_ipv6,omitempty"`
	// Gateway IPv4 address.
	GwIp string `json:"gw_ip,omitempty"`
	// Gateway IPv6 address.
	GwIpv6 string `json:"gw_ipv6,omitempty"`
	// The VLAN of the virtual IP pool.
	Vlan  int    `json:"vlan,omitempty"`
	State string `json:"state,omitempty"`
	// IDs of CNodes comprising the CNode group.
	CnodeIds []int32 `json:"cnode_ids,omitempty"`
	// Parent cluster.
	Cluster    string `json:"cluster,omitempty"`
	Url        string `json:"url,omitempty"`
	DomainName string `json:"domain_name,omitempty"`
	// Role.
	Role string `json:"role,omitempty"`
	// IP ranges.
	IpRanges [][]string `json:"ip_ranges,omitempty"`
	// If 'true', the CNodes included in this virtual IP pool are handled as preferred CNodes during VMS host election.
	VmsPreferred bool `json:"vms_preferred,omitempty"`
	// Enables or disables the virtual IP pool.
	Enabled bool `json:"enabled,omitempty"`
	// The port(s) on the CNode that this pool will use: 'Right', 'Left' or 'All'.
	PortMembership string `json:"port_membership,omitempty"`
	// The number of active interfaces.
	ActiveInterfaces int32 `json:"active_interfaces,omitempty"`
	// Enables or disables L3 CNode access.
	EnableL3 bool `json:"enable_l3,omitempty"`
	// VAST ASN.
	VastAsn int32 `json:"vast_asn,omitempty"`
	// Peer ASN.
	PeerAsn int32 `json:"peer_asn,omitempty"`
	// The ID of the tenant associated with the virtual IP pool. An ID of '0' (zero) means the virtual IP pool is available for all tenants.
	TenantId int64 `json:"tenant_id,omitempty"`
	// IDs of active CNodes
	ActiveCnodeIds []int32 `json:"active_cnode_ids,omitempty"`
	// Cluster ID
	ClusterId int32    `json:"cluster_id,omitempty"`
	Cnodes    []string `json:"cnodes,omitempty"`
	// Weighted Balancing Enabled
	EnableWeightedBalancing bool `json:"enable_weighted_balancing,omitempty"`
	// IP ranges
	RangesSummary string `json:"ranges_summary,omitempty"`
	// Synchronization time with leader
	SyncTime string `json:"sync_time,omitempty"`
	// Synchronization state with leader
	Sync string `json:"sync,omitempty"`
	// Tenant Name
	TenantName string `json:"tenant_name,omitempty"`
	// IP range of the VIP pool
	Title string `json:"title,omitempty"`
}
