/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type S3replicationPeers struct {
	// The unique ID of the S3 replication peer configuration.
	Id int64 `json:"id,omitempty"`
	// The unique GUID of the S3 replication peer configuration.
	Guid string `json:"guid,omitempty"`
	// The name of the S3 replication peer configuration.
	Name string `json:"name,omitempty"`
	// Direct URL of the S3 replication peer configuration.
	Url string `json:"url,omitempty"`
	// The name of the peer bucket to replicate to.
	BucketName string `json:"bucket_name,omitempty"`
	// The HTTP protocol used (HTTP or HTTPS).
	HttpProtocol string `json:"http_protocol,omitempty"`
	// The type of the peer bucket: CUSTOM_S3/AWS_S3
	Type_ string `json:"type"`
	// A list of HTTP proxies.
	Proxies []string `json:"proxies,omitempty"`
	// The AWS region of the bucket. Valid only when type is AWS_S3.
	AwsRegion string `json:"aws_region,omitempty"`
	// The S3 access key.
	AccessKey string `json:"access_key,omitempty"`
	// The S3 secret key.
	SecretKey string `json:"secret_key,omitempty"`
	// The S3 URL of the bucket (DNS name/IP), used only when using CUSTOM_S3.
	CustomBucketUrl string `json:"custom_bucket_url,omitempty"`
}
