/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VastDatabaseTable struct {
	// A unique id given to the database
	Id string `json:"id,omitempty"`
	// A unique guid given to the databse
	Guid string `json:"guid,omitempty"`
	// The Table name
	Name string `json:"name,omitempty"`
	// The database+schema identification
	SchemaIdentifier string `json:"schema_identifier,omitempty"`
	// The table fields at json format
	Fields string `json:"fields,omitempty"`
}
