/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ReplicationPeers struct {
	// A unique id given to the replication peer configuration
	Id int64 `json:"id,omitempty"`
	// A unique guid given to the  replication peer configuration
	Guid string `json:"guid,omitempty"`
	// The name of the replication peer configuration
	Name string `json:"name,omitempty"`
	// Direct url of the replication peer configurations
	Url string `json:"url,omitempty"`
	// The vip provided for the replication peer configuration
	LeadingVip string `json:"leading_vip,omitempty"`
	// The vip range which were reported by the peer
	RemoteVipRange string `json:"remote_vip_range,omitempty"`
	// The version of the source
	Version string `json:"version,omitempty"`
	// The version of the remote peer
	RemoteVersion string `json:"remote_version,omitempty"`
	// Is the source of the replication local (this host is the source)
	IsLocal bool `json:"is_local,omitempty"`
	// The name of the peer cluster
	PeerName string `json:"peer_name,omitempty"`
	// Is the connection secure
	SecureMode string `json:"secure_mode,omitempty"`
}
