/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ViewCreate struct {
	// A unique name for the view.
	Name string `json:"name,omitempty"`
	// File system path. Begin with '/'. Do not include a trailing slash.
	Path string `json:"path"`
	// If 'true', creates the directory specified by the path.
	CreateDir bool `json:"create_dir,omitempty"`
	// Alias for NFS export. The alias must start with '/' and can include ASCII characters only. If configured, this setting supersedes the exposed NFS export path.
	Alias string `json:"alias,omitempty"`
	// S3 bucket name.
	Bucket string `json:"bucket,omitempty"`
	// The ID of the view policy to be associated with the view.
	PolicyId int32 `json:"policy_id,omitempty"`
	// Parent cluster.
	Cluster string `json:"cluster,omitempty"`
	// Parent cluster ID.
	ClusterId int32 `json:"cluster_id,omitempty"`
	// The ID of the tenant associated with this view.
	TenantId int32 `json:"tenant_id,omitempty"`
	// If 'true', creates the directory if it does not exist.
	Directory bool `json:"directory,omitempty"`
	// Enables or disables S3 versioning.
	S3Versioning bool `json:"s3_versioning,omitempty"`
	// Allows or prohibits S3 Unverified Lookup.
	S3UnverifiedLookup bool `json:"s3_unverified_lookup,omitempty"`
	// Allows or prohibits S3 anonymous access.
	AllowAnonymousAccess bool `json:"allow_anonymous_access,omitempty"`
	// Allows or prohibits S3 anonymous access.
	AllowS3AnonymousAccess bool `json:"allow_s3_anonymous_access,omitempty"`
	// Protocols exposed by this view.
	Protocols []string `json:"protocols,omitempty"`
	// Name of the SMB share. The name cannot not include the following characters: \" \\ / [ ] : | < > + = ; , * ?
	Share string `json:"share,omitempty"`
	// S3 bucket owner.
	BucketOwner string `json:"bucket_owner,omitempty"`
	// A list of bucket creator users.
	BucketCreators []string `json:"bucket_creators,omitempty"`
	// A list of bucket creator groups.
	BucketCreatorsGroups []string `json:"bucket_creators_groups,omitempty"`
	// Enables or disables S3 object locks.
	S3Locks bool `json:"s3_locks,omitempty"`
	// S3 locks retention mode.
	S3LocksRetentionMode string `json:"s3_locks_retention_mode,omitempty"`
	// Retention period for S3 locks. The period is specified as a positive integer suffixed by a time unit of measure, for example: '0d'|'2d'|'1y'|'2y'
	S3LocksRetentionPeriod string `json:"s3_locks_retention_period,omitempty"`
	// Physical capacity.
	PhysicalCapacity int64 `json:"physical_capacity,omitempty"`
	// Logical capacity.
	LogicalCapacity int64 `json:"logical_capacity,omitempty"`
	// Indicates whether the view supports simultaneous access using NFSv3/NFSv4/SMB protocols.
	NfsInteropFlags string        `json:"nfs_interop_flags,omitempty"`
	IsRemote        bool          `json:"is_remote,omitempty"`
	ShareAcl        *ViewShareAcl `json:"share_acl,omitempty"`
	// The ID of the QoS policy associated with the view.
	QosPolicyId int32 `json:"qos_policy_id,omitempty"`
}
