/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type QuotaEntityInfo struct {
	// The name of the entity.
	Name           string `json:"name,omitempty"`
	VastId         int32  `json:"vast_id,omitempty"`
	Email          string `json:"email,omitempty"`
	IsGroup        bool   `json:"is_group"`
	Identifier     string `json:"identifier,omitempty"`
	IdentifierType string `json:"identifier_type,omitempty"`
}
