/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ViewEventNotification struct {
	// A unique name of an event among all other events related to the view holding this event
	Name string `json:"name,omitempty"`
	// The name of the kafka topic to send alert to
	Topic string `json:"topic,omitempty"`
	// The id of the external kafka broker
	BrokerId int `json:"broker_id,omitempty"`
	// List of S3 triggers which will trigger event notification, The following events are supported: - S3_OBJECT_CREATED_ALL - S3_OBJECT_CREATED_PUT - S3_OBJECT_CREATED_POST - S3_OBJECT_CREATED_COPY - S3_OBJECT_CREATED_COMPLETE_MULTIPART_UPLOAD - S3_OBJECT_REMOVED_ALL - S3_OBJECT_REMOVED_DELETE - S3_OBJECT_REMOVED_DELETE_MARKER_CREATED
	Triggers []string `json:"triggers,omitempty"`
	// Event prefix filter
	PrefixFilter string `json:"prefix_filter,omitempty"`
	// Event suffix filter
	SuffixFilter string `json:"suffix_filter,omitempty"`
}
