/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ShareAcl struct {
	Grantee     string `json:"grantee,omitempty"`
	Permissions string `json:"permissions,omitempty"`
	SidStr      string `json:"sid_str,omitempty"`
	UidOrGid    int64  `json:"uid_or_gid,omitempty"`
	Name        string `json:"name,omitempty"`
	Fqdn        string `json:"fqdn,omitempty"`
}
