/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type QoSDynamicTotalLimits struct {
	// Maximal amount of performance per GB to provide when there is no resource contention
	MaxBwMbpsPerGbCapacity int64 `json:"max_bw_mbps_per_gb_capacity,omitempty"`
	// Maximal amount of performance per GB to provide when there is no resource contention
	MaxIopsPerGbCapacity int64 `json:"max_iops_per_gb_capacity,omitempty"`
}
