/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Realm struct {
	// The unique ID of the realm.
	Id int64 `json:"id,omitempty"`
	// The unique GUID of the realm.
	Guid string `json:"guid,omitempty"`
	// The unique name of the realm.
	Name string `json:"name,omitempty"`
	// A list of permissions granted.
	ObjectTypes []string `json:"object_types,omitempty"`
}
