/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GlobalSnapshotOwnerTenant struct {
	// Ten name of the remote Tenant
	Name string `json:"name,omitempty"`
	// The remote tenant guid
	Guid string `json:"guid,omitempty"`
}
