/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Group struct {
	// The unique ID of the group.
	Id int32 `json:"id,omitempty"`
	// The unique GUID of the group.
	Guid string `json:"guid,omitempty"`
	// The unique name of the group.
	Name string `json:"name,omitempty"`
	// The Unix GID of the group.
	Gid int32 `json:"gid,omitempty"`
	// The SID of the group.
	Sid string `json:"sid,omitempty"`
	// A list of identity policy IDs.
	S3PoliciesIds []int32 `json:"s3_policies_ids,omitempty"`
}
