/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ReplicationPeers struct {
	// The unique ID of the replication peer configuration.
	Id int64 `json:"id,omitempty"`
	// The unique GUID of the replication peer configuration.
	Guid string `json:"guid,omitempty"`
	// The name of the replication peer configuration.
	Name string `json:"name,omitempty"`
	// Direct URL of the replication peer configuration.
	Url string `json:"url,omitempty"`
	// The virtual IP pool provided for the replication peer configuration.
	LeadingVip string `json:"leading_vip,omitempty"`
	// The range of virtual IPs that were reported by the peer.
	RemoteVipRange string `json:"remote_vip_range,omitempty"`
	// The version of the source.
	Version string `json:"version,omitempty"`
	// The version of the remote peer.
	RemoteVersion string `json:"remote_version,omitempty"`
	// Specifies whether the source of the replication is local (this host is the source).
	IsLocal bool `json:"is_local,omitempty"`
	// The name of the peer cluster.
	PeerName string `json:"peer_name,omitempty"`
	// If true, the connection is secure.
	SecureMode string `json:"secure_mode,omitempty"`
	// The ID of the replication virtual IP pool.
	PoolId int `json:"pool_id,omitempty"`
}
