/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProtectedPath struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	// guid
	Guid string `json:"guid,omitempty"`
	// protection policy id
	ProtectionPolicyId int32 `json:"protection_policy_id,omitempty"`
	// path to replicate
	SourceDir string `json:"source_dir,omitempty"`
	// where to replicate on the remote
	TargetExportedDir string `json:"target_exported_dir,omitempty"`
	// Local Tenant ID
	TenantId int32 `json:"tenant_id,omitempty"`
	// The Remote tenant guid
	RemoteTenantGuid string `json:"remote_tenant_guid,omitempty"`
	// The remote target object id
	TargetId int32 `json:"target_id,omitempty"`
	// Replication capabilities which define , avaliable only for cluster from version 5.1
	Capabilities string `json:"capabilities,omitempty"`
}
