/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type QoSStaticTotalLimits struct {
	// Maximal BW Mb/s
	MaxBwMbps int64 `json:"max_bw_mbps,omitempty"`
	// Burst BW Mb
	BurstBwMb int64 `json:"burst_bw_mb,omitempty"`
	// Burst loan Mb
	BurstLoanMb int64 `json:"burst_loan_mb,omitempty"`
	// Maximal IOPS
	MaxIops int64 `json:"max_iops,omitempty"`
	// Burst IOPS
	BurstIops int64 `json:"burst_iops,omitempty"`
	// Burst loan IOPS
	BurstLoanIops int64 `json:"burst_loan_iops,omitempty"`
}
