/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type KafkaBrokerAddressParams struct {
	// IP or hostname of a Kafka broker server
	Host string `json:"host,omitempty"`
	// Port of a Kafka broker server
	Port int32 `json:"port,omitempty"`
}
