/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type User struct {
	// The unique ID of the user.
	Id int32 `json:"id,omitempty"`
	// The unique GUID of the user.
	Guid string `json:"guid,omitempty"`
	// The unique name of the user.
	Name string `json:"name,omitempty"`
	// The user's Unix UID.
	Uid int32 `json:"uid,omitempty"`
	// The user's leading Unix GID.
	LeadingGid int32 `json:"leading_gid,omitempty"`
	// A list of supplementary GIDs.
	Gids []int32 `json:"gids,omitempty"`
	// A list of supplementary groups.
	Groups []string `json:"groups,omitempty"`
	// Group count.
	GroupCount int32 `json:"group_count,omitempty"`
	// The name of the leading group.
	LeadingGroupName string `json:"leading_group_name,omitempty"`
	// The GID of the leading group.
	LeadingGroupGid int `json:"leading_group_gid,omitempty"`
	// The user's SID.
	Sid string `json:"sid,omitempty"`
	// The user's primary group SID.
	PrimaryGroupSid string `json:"primary_group_sid,omitempty"`
	// A list of supplementary SIDs.
	Sids []string `json:"sids,omitempty"`
	// If 'true', the user is a local user.
	Local bool `json:"local,omitempty"`
	// Allows or prohibits bucket creation by the user.
	AllowCreateBucket bool `json:"allow_create_bucket,omitempty"`
	// Allows or prohibits bucket deletion by the user.
	AllowDeleteBucket bool `json:"allow_delete_bucket,omitempty"`
	// If 'true', the user is an S3 superuser.
	S3Superuser bool `json:"s3_superuser,omitempty"`
	// A list of identity policy IDs.
	S3PoliciesIds []int32 `json:"s3_policies_ids,omitempty"`
}
