/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NisrPost struct {
	// The nis server domain name
	DomainName string `json:"domain_name,omitempty"`
	// List of ip addresses/hostnames of nis servers
	Hosts []string `json:"hosts,omitempty"`
}
