/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BlockMapping struct {
	// A unique id given to the blockhost
	Id int64 `json:"id,omitempty"`
	// A uniqe GUID assigned to the blockhost
	Guid string `json:"guid,omitempty"`
	// The Volume ID to map the blockhost to
	Volume string `json:"volume,omitempty"`
	// The blockhost id to map to this volume
	BlockHost string `json:"block_host,omitempty"`
	// If configured with a snapshot of the volume than the blockhost will be mapped to this snapshot
	SnapshotId int64 `json:"snapshot_id,omitempty"`
}
