/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BucketLogging struct {
	// The ID of the logging bucket.
	DestinationId int64 `json:"destination_id,omitempty"`
	// Log line prefix to add
	Prefix string `json:"prefix,omitempty"`
	// The format for log object keys: 'SIMPLE_PREFIX=[DestinationPrefix][YYYY]-[MM]-[DD]-[hh]-[mm]-[ss]-[UniqueString]', 'PARTITIONED_PREFIX_EVENT_TIME=[DestinationPrefix][SourceUsername]/[SourceBucket]/[YYYY]/[MM]/[DD]/[YYYY]-[MM]-[DD]-[hh]-[mm]-[ss]-[UniqueString]' where the partitioning is done based on the time when the logged events occurred, 'PARTITIONED_PREFIX_DELIVERY_TIME=[DestinationPrefix][SourceUsername]/[SourceBucket]/[YYYY]/[MM]/[DD]/[YYYY]-[MM]-[DD]-[hh]-[mm]-[ss]-[UniqueString]' where the partitioning is done based on the time when the log object has been delivered to the destination bucket. Default: 'SIMPLE_PREFIX'.
	KeyFormat string `json:"key_format,omitempty"`
}
