/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Kafkabroker struct {
	// A unique number given to the kafkabroker
	Id int32 `json:"id,omitempty"`
	// A GUID given to the kafkabroker
	Guid string `json:"guid,omitempty"`
	// The name of the Kafka broker
	Name string `json:"name,omitempty"`
	// The tenant id to associate with this kafkabroker
	TenantId int64 `json:"tenant_id,omitempty"`
	// List of Kafka server addresses
	Addresses []KafkaBrokerAddressParams `json:"addresses,omitempty"`
}
