/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Ldap struct {
	Id int32 `json:"id,omitempty"`
	Guid string `json:"guid,omitempty"`
	// List of URIs of LDAP servers (Domain Controllers (DCs) in Active Directory), in priority order. The URI with highest priority that has a good health status is used. Specify each URI in the format <scheme>://<address>. <address> can be either a DNS name or an IP address. e.g. ldap://ldap.company.com, ldaps://ldaps.company.com, ldap://192.0.2.2
	Urls []string `json:"urls,omitempty"`
	// LDAP server port. 389 (LDAP)  636 (LDAPS)
	Port int32 `json:"port,omitempty"`
	// Distinguished name of LDAP superuser
	Binddn string `json:"binddn,omitempty"`
	// Password for the LDAP superuser
	Bindpw string `json:"bindpw,omitempty"`
	// The Base DN is the starting point the LDAP provider uses when searching for users and groups. If the Group Base DN is configured it will be used instead of the Base DN, for groups only
	Searchbase string `json:"searchbase,omitempty"`
	// Base DN for group queries within the joined domain only. When auto discovery is enabled, group queries outside the joined domain use auto-discovered Base DNs.
	GroupSearchbase string `json:"group_searchbase,omitempty"`
	// Bind Authentication Method
	Method string `json:"method,omitempty"`
	// Attrirbute mapping for gid number
	GidNumber string `json:"gid_number,omitempty"`
	// Attrirbute mapping for uid
	Uid string `json:"uid,omitempty"`
	// Attrirbute mapping for uid number
	UidNumber string `json:"uid_number,omitempty"`
	// Attribute mapping for user matching
	MatchUser string `json:"match_user,omitempty"`
	// Attrirbute mapping for uid member
	UidMember string `json:"uid_member,omitempty"`
	// Attrirbute mapping for posix account
	PosixAccount string `json:"posix_account,omitempty"`
	// Attrirbute mapping for posix account
	PosixGroup string `json:"posix_group,omitempty"`
	// configure LDAP with TLS
	UseTls bool `json:"use_tls,omitempty"`
	// POSIX primary provider
	PosixPrimaryProvider bool `json:"posix_primary_provider,omitempty"`
	PosixAttributesSource string `json:"posix_attributes_source,omitempty"`
	ReverseLookup bool `json:"reverse_lookup,omitempty"`
	TlsCertificate string `json:"tls_certificate,omitempty"`
	ActiveDirectory string `json:"active_directory,omitempty"`
	// Query group mode
	QueryGroupsMode string `json:"query_groups_mode,omitempty"`
	// Username property name
	UsernamePropertyName string `json:"username_property_name,omitempty"`
	// FQDN of the domain.
	DomainName string `json:"domain_name,omitempty"`
	// The attribute used to query AD for the user login name in NFS ID mapping. Applicable only with AD and NFSv4.1.
	UserLoginName string `json:"user_login_name,omitempty"`
	// The attribute used to query AD for the group login name in NFS ID mapping. Applicable only with AD and NFSv4.1.
	GroupLoginName string `json:"group_login_name,omitempty"`
	MailPropertyName string `json:"mail_property_name,omitempty"`
	UidMemberValuePropertyName string `json:"uid_member_value_property_name,omitempty"`
	// When enabled, Active Directory Domain Controllers (DCs) and Active Directory domains are auto discovered. Queries extend beyond the joined domain to all domains in the forest. When disabled, queries are restricted to the joined domain and DCs must be provided in the URLs field.
	UseAutoDiscovery bool `json:"use_auto_discovery,omitempty"`
	// Use LDAPS for Auto-Discovery
	UseLdaps bool `json:"use_ldaps,omitempty"`
	// Whether the LDAP should be used for VMS auth. There is only two LDAPs allowed for VMS auth: one with AD and one w/o.
	IsVmsAuthProvider bool `json:"is_vms_auth_provider,omitempty"`
	// When set to True - users/groups from non-joined domain POSIX attributes are supported, when set to False - Posix attributes of users/groups from non-joined domain are not supported. As a condition Global catalog needs to be configured to support Posix attributes. 
	QueryPosixAttributesFromGc bool `json:"query_posix_attributes_from_gc,omitempty"`
}
