/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DefaultQuota struct {
	// The system ID of the quota.
	QuotaSystemId int32 `json:"quota_system_id,omitempty"`
	// The soft limit for capacity in bytes.
	SoftLimit int64 `json:"soft_limit,omitempty"`
	// The hard limit for capacity in bytes.
	HardLimit int64 `json:"hard_limit,omitempty"`
	// The soft limit for the number of inodes.
	SofLimitInodes int64 `json:"sof_limit_inodes,omitempty"`
	// The hard limit for the number of inodes.
	HardLimitInodes int64 `json:"hard_limit_inodes,omitempty"`
	// Quota enforcement grace period in the format of HH:MM:SS.
	GracePeriod string `json:"grace_period,omitempty"`
}
