/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Manager struct {
	// A unique id given to the manager
	Id int64 `json:"id,omitempty"`
	// A uniqe GUID assigned to the manager
	Guid string `json:"guid,omitempty"`
	// The username of the manager
	Username string `json:"username,omitempty"`
	// The username of the manager
	Password string `json:"password,omitempty"`
	// The user firstname
	FirstName string `json:"first_name,omitempty"`
	// The user last name
	LastName string `json:"last_name,omitempty"`
	// List of allowed permissions
	PermissionsList []string `json:"permissions_list,omitempty"`
	// List of roles ids
	Roles []int `json:"roles,omitempty"`
	// Disable password expiration
	PasswordExpirationDisabled bool `json:"password_expiration_disabled,omitempty"`
	// If this set to true next time that a user will login he will be promped to replace his password
	IsTemporaryPassword bool `json:"is_temporary_password,omitempty"`
	// List of allowed permissions returned from the VMS
	Permissions []string `json:"permissions,omitempty"`
}
