/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PermissionsPerVipPool struct {
	// The ID of the virtual IP pool.
	VippoolId string `json:"vippool_id,omitempty"`
	// Permissions for the virtual IP pool.
	VippoolPermissions string `json:"vippool_permissions,omitempty"`
}
