/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProtectionPolicy struct {
	// The unique ID of the protection policy.
	Id int64 `json:"id,omitempty"`
	// The unique GUID of the protection policy.
	Guid string `json:"guid,omitempty"`
	// The name of the protection policy.
	Name string `json:"name,omitempty"`
	// Direct URL of the protection policy.
	Url string `json:"url,omitempty"`
	// The name of the destination peer.
	TargetName string `json:"target_name,omitempty"`
	// The ID of the destination peer.
	TargetObjectId int `json:"target_object_id,omitempty"`
	// The prefix to be given to the replicated data.
	Prefix string `json:"prefix,omitempty"`
	// The type of replication.
	CloneType string `json:"clone_type,omitempty"`
	// A list of snapshot schedules.
	Frames []ProtectionPolicySchedule `json:"frames,omitempty"`
	// If true, the snapshot is  indestructable.
	Indestructible bool `json:"indestructible,omitempty"`
}
