/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type QoSStaticTotalLimits struct {
	// Maximum bandwidth (in MB/s).
	MaxBwMbps int64 `json:"max_bw_mbps,omitempty"`
	// Burst bandwidth (in MB/s)
	BurstBwMb int64 `json:"burst_bw_mb,omitempty"`
	// Burst credits (in MB/s)
	BurstLoanMb int64 `json:"burst_loan_mb,omitempty"`
	// Maximum IOPS.
	MaxIops int64 `json:"max_iops,omitempty"`
	// Burst IOPS.
	BurstIops int64 `json:"burst_iops,omitempty"`
	// Burst IOPS credits.
	BurstLoanIops int64 `json:"burst_loan_iops,omitempty"`
}
