/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ActiveDirectory2 struct {
	Id int32 `json:"id,omitempty"`
	Guid string `json:"guid,omitempty"`
	MachineAccountName string `json:"machine_account_name,omitempty"`
	OrganizationalUnit string `json:"organizational_unit,omitempty"`
	SmbAllowed bool `json:"smb_allowed,omitempty"`
	NtlmEnabled bool `json:"ntlm_enabled,omitempty"`
	UseAutoDiscovery bool `json:"use_auto_discovery,omitempty"`
	UseLdaps bool `json:"use_ldaps,omitempty"`
	Port int `json:"port,omitempty"`
	Binddn string `json:"binddn,omitempty"`
	Searchbase string `json:"searchbase,omitempty"`
	DomainName string `json:"domain_name,omitempty"`
	Method string `json:"method,omitempty"`
	QueryGroupsMode string `json:"query_groups_mode,omitempty"`
	PosixAttributesSource string `json:"posix_attributes_source,omitempty"`
	UseTls bool `json:"use_tls,omitempty"`
	ReverseLookup bool `json:"reverse_lookup,omitempty"`
	GidNumber string `json:"gid_number,omitempty"`
	UseMultiForest bool `json:"use_multi_forest,omitempty"`
	Uid string `json:"uid,omitempty"`
	UidNumber string `json:"uid_number,omitempty"`
	MatchUser string `json:"match_user,omitempty"`
	UidMemberValuePropertyName string `json:"uid_member_value_property_name,omitempty"`
	UidMember string `json:"uid_member,omitempty"`
	PosixAccount string `json:"posix_account,omitempty"`
	PosixGroup string `json:"posix_group,omitempty"`
	UsernamePropertyName string `json:"username_property_name,omitempty"`
	UserLoginName string `json:"user_login_name,omitempty"`
	GroupLoginName string `json:"group_login_name,omitempty"`
	MailPropertyName string `json:"mail_property_name,omitempty"`
	IsVmsAuthProvider bool `json:"is_vms_auth_provider,omitempty"`
	Bindpw string `json:"bindpw,omitempty"`
	// List of LDAP servers urls , starting with ldap://
	Urls []string `json:"urls,omitempty"`
	// When creating an active directory using this resource an ldap configuration is also created if set to true than whed deleting this resource the ldap configuration will be kept otherwise it will also be deleted
	SkipLdap string `json:"skip_ldap,omitempty"`
}
