/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VastDatabaseSchema struct {
	// A unique id given to the database
	Id string `json:"id,omitempty"`
	// A unique guid given to the databse
	Guid string `json:"guid,omitempty"`
	// The name of the database schema
	DatabaseName string `json:"database_name,omitempty"`
	// The databse schema name
	Name string `json:"name,omitempty"`
	// A computed identifier of the table
	Identifier string `json:"identifier,omitempty"`
}
