/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VastDatabase struct {
	// A unique id given to the database
	Id int64 `json:"id,omitempty"`
	// A unique guid given to the databse
	Guid string `json:"guid,omitempty"`
	// The bucket name that will hold the database
	Bucket string `json:"bucket,omitempty"`
	// The user name who should own this bucket
	BucketOwner string `json:"bucket_owner,omitempty"`
	// The view path which be used for this database
	Path string `json:"path,omitempty"`
	// The ID of the view policy to associate with this database (the policy must contains the S3 protocol)
	PolicyId int64 `json:"policy_id,omitempty"`
	// The tenant ID of the view policy which is associated with this database
	TenantId int64 `json:"tenant_id,omitempty"`
}
