/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Volume struct {
	// A unique id given to the manager
	Id int64 `json:"id,omitempty"`
	// A uniqe GUID assigned to the manager
	Guid string `json:"guid,omitempty"`
	// A uniqe name given to the volume
	Name string `json:"name,omitempty"`
	// The volume size of the volume in bytes
	Size int64 `json:"size,omitempty"`
	// The View ID to relate this volume with , must be a View with protocol defined as BLOCK
	ViewId int64 `json:"view_id,omitempty"`
	// List of blockhosts associated with this volume
	BlockHostIds []int64 `json:"block_host_ids,omitempty"`
	// List of tags at the key:value format
	VolumeTags []string `json:"volume_tags,omitempty"`
}
