/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BlockMapping struct {
	// A unique id given to the blockhost
	Id string `json:"id,omitempty"`
	// The Volume ID to map the blockhost to
	VolumeId int64 `json:"volume_id,omitempty"`
	// The blockhost id to map to this volume
	HostsIds []int64 `json:"hosts_ids,omitempty"`
	// If configured with a snapshot of the volume than the blockhost will be mapped to this snapshot
	SnapshotId int64 `json:"snapshot_id,omitempty"`
}
