/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BlockHost struct {
	// A unique id given to the blockhost
	Id int64 `json:"id,omitempty"`
	// A uniqe GUID assigned to the blockhost
	Guid string `json:"guid,omitempty"`
	// A uniqe name given to the blockhost
	Name string `json:"name,omitempty"`
	// The tenant id of which this blockhost belongs to
	TenantId int64 `json:"tenant_id,omitempty"`
	ConnectionType string `json:"connection_type,omitempty"`
	// The blockhost NQN (NVMe Qualified Name)
	Nqn string `json:"nqn,omitempty"`
	// List of tags at the key:value format
	BlockhostTags []string `json:"blockhost_tags,omitempty"`
}
