/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserQuotaModifyParams struct {
	// Quota enforcement grace period. An alarm is triggered and write operations are blocked if storage usage continues to exceed the soft limit for the grace period. Format: [DD] [HH:[MM:]]s
	GracePeriod string `json:"grace_period,omitempty"`
	// Storage usage limit at which warnings of exceeding the quota are issued.
	SoftLimit string `json:"soft_limit,omitempty"`
	// Storage usage limit beyond which no writes will be allowed.
	HardLimit string `json:"hard_limit,omitempty"`
	// Number of directories and unique files under the path beyond which no writes will be allowed. A file with multiple hardlinks is counted only once.
	HardLimitInodes int32 `json:"hard_limit_inodes,omitempty"`
	// Number of directories and unique files under the path at which warnings of exceeding the quota will be issued. A file with multiple hardlinks is counted only once.
	SoftLimitInodes int32 `json:"soft_limit_inodes,omitempty"`
}
