/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AsyncGlobalSnapStream struct {
	// 
	Id int32 `json:"id,omitempty"`
	// unique identifier
	Guid string `json:"guid,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// Remote cluster name
	RemoteTarget string `json:"remote_target,omitempty"`
	// Owner root snapshot details
	OwnerRootSnapshot *interface{} `json:"owner_root_snapshot,omitempty"`
	// Loanee snapshot name
	LoaneeSnapshot string `json:"loanee_snapshot,omitempty"`
	// Target path
	LoaneeRootPath string `json:"loanee_root_path,omitempty"`
	// Status
	Status *interface{} `json:"status,omitempty"`
	// Enabled
	Enabled bool `json:"enabled,omitempty"`
	// Target cluster
	TargetCluster string `json:"target_cluster,omitempty"`
	// Source cluster
	SourceCluster string `json:"source_cluster,omitempty"`
	// Source snapshot
	SourceSnapshot string `json:"source_snapshot,omitempty"`
	// ETA
	Eta string `json:"eta,omitempty"`
	// Creation Async task properties
	AsyncTask *interface{} `json:"async_task,omitempty"`
}
