/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ReplicationStreamModifyParams struct {
	// 
	Name string `json:"name,omitempty"`
	// state
	State string `json:"state,omitempty"`
	// path to replicate
	SourceDir string `json:"source_dir,omitempty"`
	// replication policy id
	ReplicationPolicyId string `json:"replication_policy_id,omitempty"`
	// protection policy id
	ProtectionPolicyId string `json:"protection_policy_id,omitempty"`
	// enable/pause replication stream
	Enabled bool `json:"enabled,omitempty"`
}
