/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ShouldUploadParams struct {
	// sha256 sum of bundle
	BundleSha256 string `json:"bundle_sha256,omitempty"`
}
