/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AddBoxesParamsDboxes struct {
	Hosts *AddBoxesDBoxesHostsParams `json:"hosts"`
	Subnet int32 `json:"subnet"`
	Order int32 `json:"order"`
}
