/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Module struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// Module Type (I, E, ...)
	ModuleType string `json:"module_type,omitempty"`
	// Env ID
	EnvId int32 `json:"env_id,omitempty"`
	// 
	State string `json:"state,omitempty"`
	// Silo ID
	SiloId int32 `json:"silo_id,omitempty"`
	// Parent Env
	Env string `json:"env,omitempty"`
	// Parent CNode
	Cnode string `json:"cnode,omitempty"`
	// Parent DNode
	Dnode string `json:"dnode,omitempty"`
	// Parent Cluster
	Cluster string `json:"cluster,omitempty"`
	// 
	Url string `json:"url,omitempty"`
}
