/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProtectedPath struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// guid
	Guid string `json:"guid,omitempty"`
	// state
	State string `json:"state,omitempty"`
	// replication policy id
	ReplicationPolicy string `json:"replication_policy,omitempty"`
	// protection policy id
	ProtectionPolicyId string `json:"protection_policy_id,omitempty"`
	// protection policy name
	ProtectionPolicyName string `json:"protection_policy_name,omitempty"`
	// start/pause replication
	Enabled bool `json:"enabled,omitempty"`
	// path to replicate
	SourceDir string `json:"source_dir,omitempty"`
	// where to replicate on the remote
	TargetExportedDir string `json:"target_exported_dir,omitempty"`
	// Trigger failover command
	Failover bool `json:"failover,omitempty"`
	// current role in the replication
	Role string `json:"role,omitempty"`
	// 
	Internal bool `json:"internal,omitempty"`
	// 
	Health string `json:"health,omitempty"`
	// 
	LastRestorePointCreationTime string `json:"last_restore_point_creation_time,omitempty"`
	// 
	LastUploadingRestorePointState string `json:"last_uploading_restore_point_state,omitempty"`
	// 
	LastUploadingRestorePointPhysicalSize string `json:"last_uploading_restore_point_physical_size,omitempty"`
	// 
	LastUploadingRestorePointLogicalSize string `json:"last_uploading_restore_point_logical_size,omitempty"`
	// 
	Eta string `json:"eta,omitempty"`
	// 
	InodeCount string `json:"inode_count,omitempty"`
	// 
	Progress string `json:"progress,omitempty"`
	// Replication Bandwidth
	Bw int64 `json:"bw,omitempty"`
	// 
	FailbackAllowed string `json:"failback_allowed,omitempty"`
	// The usable capacity reclaimable by deleting all of its snapshots
	AggrPhysEstimation int64 `json:"aggr_phys_estimation,omitempty"`
	// Local Tenant ID
	TenantId int32 `json:"tenant_id,omitempty"`
	// Local Tenant name
	TenantName string `json:"tenant_name,omitempty"`
	// remote tenant name
	RemoteTenantName string `json:"remote_tenant_name,omitempty"`
	// remote tenant guid
	RemoteTenantGuid string `json:"remote_tenant_guid,omitempty"`
}
