/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EventAddParams struct {
	// 
	EventMessage string `json:"event_message,omitempty"`
	// 
	EventType string `json:"event_type,omitempty"`
	// 
	ObjectType string `json:"object_type"`
	// 
	ObjectId string `json:"object_id"`
}
