/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EventDefinition struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	ObjectType string `json:"object_type,omitempty"`
	// 
	EventType string `json:"event_type,omitempty"`
	// The severity of the alarm
	Severity string `json:"severity,omitempty"`
	// Trigger to turn on the alarm
	TriggerOn string `json:"trigger_on,omitempty"`
	// Trigger to turn off the alarm
	TriggerOff string `json:"trigger_off,omitempty"`
	// Did a user modify this event definition
	UserModified bool `json:"user_modified,omitempty"`
	// Time frame for rate alarms
	TimeFrame string `json:"time_frame,omitempty"`
	// List of emails you want to notify in case this alarm occurs (separated by comma)
	EmailRecipients string `json:"email_recipients,omitempty"`
	// The URL that the webhook will go to
	WebhookUrl string `json:"webhook_url,omitempty"`
	// Use $event as event message parameter
	WebhookData string `json:"webhook_data,omitempty"`
	// The method that the webhook will use
	WebhookMethod string `json:"webhook_method,omitempty"`
	// 
	Property string `json:"property,omitempty"`
	// 
	WebhookParams string `json:"webhook_params,omitempty"`
	// 
	AlarmDefinitions string `json:"alarm_definitions,omitempty"`
	// 
	ActionDefinitions string `json:"action_definitions,omitempty"`
	// 
	EventMessage string `json:"event_message,omitempty"`
	// 
	DisableActions bool `json:"disable_actions,omitempty"`
	// 
	Enable bool `json:"enable,omitempty"`
	// 
	Internal bool `json:"internal,omitempty"`
	// When this is enabled, only alarms will lead to email and webhook actions
	AlarmOnly bool `json:"alarm_only,omitempty"`
	// 
	Metadata *interface{} `json:"metadata,omitempty"`
}
