/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InjectionCreateParams struct {
	// 
	Name string `json:"name,omitempty"`
	// 
	Type_ string `json:"type,omitempty"`
	// 
	Params *interface{} `json:"params,omitempty"`
}
