/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SubnetManager struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Ips []string `json:"ips,omitempty"`
	// 
	FailureReason string `json:"failure_reason,omitempty"`
	// 
	State string `json:"state,omitempty"`
}
