/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NisCreateParams struct {
	// NIS name
	Name string `json:"name,omitempty"`
	// The NIS domain name shared by all the NIS servers and clients on your network.
	DomainName string `json:"domain_name,omitempty"`
	// Host names of NIS master and slave servers.
	Hosts []ErrorUnknown `json:"hosts,omitempty"`
	// IP addresses of NIS master and slave servers.
	Ips []ErrorUnknown `json:"ips,omitempty"`
	// NIS master and slave servers (limited to ten servers). You can specify each server by its IP or host name, up to 48 characters. Separate hosts with commas.
	Servers []ErrorUnknown `json:"servers,omitempty"`
}
