/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NisModifyParams struct {
	// NIS name
	Name string `json:"name,omitempty"`
	// domain name
	DomainName string `json:"domain_name,omitempty"`
	// list of hosts
	Hosts []ErrorUnknown `json:"hosts,omitempty"`
	// list of ips
	Ips []ErrorUnknown `json:"ips,omitempty"`
	// list of servers
	Servers []ErrorUnknown `json:"servers,omitempty"`
}
