/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ClusterWipeParams struct {
	// The list of C-Nodes
	CnodeList []CNode `json:"cnode_list,omitempty"`
	// The list of DNodes
	DnodeList []DNode `json:"dnode_list,omitempty"`
	// Loopback (single node) installation
	Loopback bool `json:"loopback,omitempty"`
	// Loopback IP
	LoopbackIp string `json:"loopback_ip,omitempty"`
	// Loopback User
	LoopbackUser string `json:"loopback_user,omitempty"`
}
