/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AddRemoteMappingParams struct {
	// Peer name
	Peer string `json:"peer,omitempty"`
	// Remote policy name
	RemotePolicy string `json:"remote_policy,omitempty"`
}
