/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DeltaConfig struct {
	// enable/disable delta
	Enabled bool `json:"enabled"`
	// prefix to ignore objects in delta
	IgnoredObjectsPrefix string `json:"ignored_objects_prefix"`
}
