/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ClusterPasswordParams struct {
	// The given username for password change
	Username string `json:"username,omitempty"`
	// The new given password
	Password string `json:"password,omitempty"`
}
