/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AddBoxesParams struct {
	Cboxes *AddBoxesParamsCboxes `json:"cboxes"`
	Dboxes *AddBoxesParamsDboxes `json:"dboxes"`
	DnodeManagementIpPool []string `json:"dnode_management_ip_pool"`
	CnodeManagementIpPool []string `json:"cnode_management_ip_pool"`
	DnodeIpmiPool []string `json:"dnode_ipmi_pool"`
	CnodeIpmiPool []string `json:"cnode_ipmi_pool"`
	ManagementCidr int32 `json:"management_cidr"`
	Ipv6Prefix int32 `json:"ipv6_prefix,omitempty"`
	ExternalGateway []string `json:"external_gateway"`
	EmptyDbox bool `json:"empty_dbox"`
	// CNode start index valid range: [1, 99], for null value index will be selected automatically, as max_existed_index + 1
	CnodeStartIndex int32 `json:"cnode_start_index,omitempty"`
	// CNode start index valid range: [100, 254], for null value index will be selected automatically, as max_existed_index + 1
	DnodeStartIndex int32 `json:"dnode_start_index,omitempty"`
	HostnamePrefix string `json:"hostname_prefix,omitempty"`
}
