/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ClusterLocksParams struct {
	// The full path to a locked file, formed as: <view path>/<filepath>, where <view path> is the VAST Cluster view path, and <filepath> is the client path to a locked file, relative to the mount point.
	Path string `json:"path,omitempty"`
}
