/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type License struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// 
	State string `json:"state,omitempty"`
	// 
	StartDate string `json:"start_date,omitempty"`
	// 
	ExpirationDate string `json:"expiration_date,omitempty"`
	// 
	Period string `json:"period,omitempty"`
	// 
	Capacity string `json:"capacity,omitempty"`
	// 
	LicenseKey string `json:"license_key,omitempty"`
}
