/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Port struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// Port title
	Title string `json:"title,omitempty"`
	// Parent Cluster
	Cluster string `json:"cluster,omitempty"`
	// Parent Switch
	Switch_ string `json:"switch,omitempty"`
	// Port state
	State string `json:"state,omitempty"`
	// Port role
	Model string `json:"model,omitempty"`
	// Port speed
	Speed string `json:"speed,omitempty"`
	// Port MTU
	Mtu string `json:"mtu,omitempty"`
}
