/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UpgradeWithoutFileParams struct {
	// Enables data reduction (DR) for a cluster without DR enabled prior to upgrade
	EnableDr bool `json:"enable_dr,omitempty"`
	// Forces upgrade regardless of version or upgrade state
	Force bool `json:"force,omitempty"`
	// Upgrade FWs: BMC, MCU, PCI, NIC
	FwUpgrade bool `json:"fw_upgrade,omitempty"`
	// Resets the configuration of isolated CPUs according to a formula
	Isolcpus bool `json:"isolcpus,omitempty"`
	// Skips validation of hardware component health. Use with caution since component redundancy is important in NDU. Do not use with OS upgrade.
	SkipHwCheck bool `json:"skip_hw_check,omitempty"`
	// Performs OS upgrade on CNodes and DNodes in addition to upgrading core platform build
	OsUpgrade bool `json:"os_upgrade,omitempty"`
	// Overrides default percentage of CNodes to upgrade in parallel. Max 50
	CnodesBatchSizePercentage int32 `json:"cnodes_batch_size_percentage,omitempty"`
	// Overrides default percentage of DNodes to upgrade in parallel. Max 37.5. Not relevant during os upgrade
	DnodesBatchSizePercentage float32 `json:"dnodes_batch_size_percentage,omitempty"`
}
