/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NativeReplicationRemoteTargetModifyParams struct {
	// 
	Name string `json:"name,omitempty"`
	// remote vips
	RemoteVips []ErrorUnknown `json:"remote_vips,omitempty"`
	// Any one of the IP addresses that belong to the remote peer's replication VIP pool. This IP is used for the initial connection between the peers.
	LeadingVip string `json:"leading_vip,omitempty"`
	// Not yet implemented
	Password string `json:"password,omitempty"`
	// 
	Version string `json:"version,omitempty"`
	// The ID of the local replication VIP Pool
	PoolId int32 `json:"pool_id,omitempty"`
	// Native Replication Remote Target ID
	Id int32 `json:"id,omitempty"`
	// Not yet implemented
	PeerCertificate string `json:"peer_certificate,omitempty"`
	// Maximum segment size (MSS), in bytes, that the peer can receive in a single TCP segment.
	Mss int32 `json:"mss,omitempty"`
	// Secure mode
	SecureMode string `json:"secure_mode,omitempty"`
}
