/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DBox struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// 
	Name string `json:"name"`
	// Unique h/w identifier
	Uid string `json:"uid,omitempty"`
	// 
	State string `json:"state,omitempty"`
	// Parent Cluster
	Cluster string `json:"cluster,omitempty"`
	// Description
	Description string `json:"description,omitempty"`
	Dnodes []DNode `json:"dnodes,omitempty"`
	// 
	Url string `json:"url,omitempty"`
	// Synchronization state with leader
	Sync string `json:"sync,omitempty"`
	// Synchronization time with leader
	SyncTime string `json:"sync_time,omitempty"`
	// Flag that indicates a replacement conclude possibility
	IsConcludePossible bool `json:"is_conclude_possible,omitempty"`
	// Flag that indicates DBox replacement availability
	IsReplacePossible bool `json:"is_replace_possible,omitempty"`
}
