/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Env struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// env type
	EnvType string `json:"env_type,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// Env ID
	EnvId int32 `json:"env_id,omitempty"`
	// 
	State string `json:"state,omitempty"`
	// Port Number
	Port int32 `json:"port,omitempty"`
	// Number of Silos
	SiloCount int32 `json:"silo_count,omitempty"`
	// Parent CNode
	Cnode string `json:"cnode,omitempty"`
	// Parent DNode
	Dnode string `json:"dnode,omitempty"`
	// Parent Cluster
	Cluster string `json:"cluster,omitempty"`
	// 
	Url string `json:"url,omitempty"`
}
