/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MonitorModifyParams struct {
	// 
	FromTime string `json:"from_time,omitempty"`
	// 
	ToTime string `json:"to_time,omitempty"`
	// Specific objects to include in the report, specified as a comma separated list of object IDs.
	ObjectIds string `json:"object_ids,omitempty"`
	// A list of metrics to query. To get the full list of metrics, use GET /metrics/.
	PropList string `json:"prop_list,omitempty"`
	// Data granularity: seconds (raw), minutes (five minute aggregated samples), hours (hourly aggregated samples), or days (daily aggregated samples)
	Granularity string `json:"granularity,omitempty"`
	// If data granularity is minutes, hours or days, the data is aggregated. This parameter selects which aggregation function to use.
	Aggregation string `json:"aggregation,omitempty"`
}
