/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProtectionPolicy struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// 
	Title string `json:"title,omitempty"`
	// unique identifier
	Guid string `json:"guid,omitempty"`
	// target object id
	TargetObjectId int32 `json:"target_object_id,omitempty"`
	// Target Name
	TargetName string `json:"target_name,omitempty"`
	// schedules
	Frames *interface{} `json:"frames,omitempty"`
	// The prefix of the snapshot that will be created
	Prefix string `json:"prefix,omitempty"`
	// Specify the type of data protection. CLOUD_REPLICATION is S3 backup. LOCAL means local snapshots without replication. (LOCAL | NATIVE_REPLICATION | CLOUD_REPLICATION)
	CloneType string `json:"clone_type,omitempty"`
	// State of Protection Policy
	State string `json:"state,omitempty"`
	// 
	Internal bool `json:"internal,omitempty"`
	// Indestructible the Protection policy from being deleted
	Indestructible bool `json:"indestructible,omitempty"`
}
