/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RemoteTenant struct {
	// Remote Tenant name
	Name string `json:"name,omitempty"`
	// Remote Tenant guid
	Guid string `json:"guid,omitempty"`
}
