/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RoleModifyParams struct {
	// Realm
	Realm string `json:"realm,omitempty"`
	// 
	Permissions string `json:"permissions,omitempty"`
	// Specify permissions list as an array of permission codenames in the format <permission>-<realm>. To list permission codenames, run /permissions/get.
	PermissionsList string `json:"permissions_list,omitempty"`
	// object type
	ObjectType string `json:"object_type,omitempty"`
	// object ID
	ObjectId string `json:"object_id,omitempty"`
	LdapGroups []ErrorUnknown `json:"ldap_groups,omitempty"`
	TenantIds []ErrorUnknown `json:"tenant_ids,omitempty"`
}
