/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LdapCreateParams struct {
	// LDAP server URI in the format <scheme>://<address>. <address> can be either a DNS name or an IP address. Example: ldap://ldap.company.com
	Url string `json:"url,omitempty"`
	// Comma separated list of URIs of LDAP servers in the format <scheme>://<address>. The order of listing defines the priority order. The URI with highest priority that has a good health status is used.
	Urls []ErrorUnknown `json:"urls,omitempty"`
	// The port of the remote LDAP server. Typical values: 389, 636.
	Port int32 `json:"port,omitempty"`
	// The bind DN for authenticating to the LDAP domain. You can specify any user account that has read access to the domain.
	Binddn string `json:"binddn,omitempty"`
	// The password used with the Bind DN to authenticate to the LDAP server.
	Bindpw string `json:"bindpw,omitempty"`
	// The entry in the LDAP directory tree to use as a starting point for user queries.
	Searchbase string `json:"searchbase,omitempty"`
	// Base DN for group queries within the joined domain only. When auto discovery is enabled, group queries outside the joined domain use auto-discovered Base DNs.
	GroupSearchbase string `json:"group_searchbase,omitempty"`
	// The authentication method configured on the LDAP server for authenticating clients. 
	Method string `json:"method,omitempty"`
	// The attribute of a group entry on the LDAP server that contains the GID number of a group, if different from 'gidNumber'. When binding VAST Cluster to AD, you may need to set this to 'gidnumber' (case sensitive).
	GidNumber string `json:"gid_number,omitempty"`
	// The attribute of a user entry on the LDAP server that contains the user name, if different from 'uid'  When binding VAST Cluster to AD, you may need to set this to 'sAMAccountname'.
	Uid string `json:"uid,omitempty"`
	// The attribute of a user entry on the LDAP server that contains the UID number, if different from 'uidNumber'. Often when binding VAST Cluster to AD this does not need to be set.
	UidNumber string `json:"uid_number,omitempty"`
	// The attribute to use when querying a provider for a user that matches a user that was already retrieved from another provider. A user entry that contains a matching value in this attribute will be considered the same user as the user previously retrieved.
	MatchUser string `json:"match_user,omitempty"`
	// The attribute of a group entry on the LDAP server that contains names of group members, if different from 'memberUid'. When binding VAST Cluster to AD, you may need to set this to 'memberUID'.
	UidMember string `json:"uid_member,omitempty"`
	// The object class that defines a user entry on the LDAP server, if different from 'posixAccount'. When binding VAST Cluster to AD, set this parameter to 'user' in order for authorization to work properly.
	PosixAccount string `json:"posix_account,omitempty"`
	// The object class that defines a group entry on the LDAP server, if different from 'posixGroup'. When binding VAST Cluster to AD, set this parameter to 'group' in order for authorization to work properly.
	PosixGroup string `json:"posix_group,omitempty"`
	// TLS certificate to use for verifying the remote LDAP server's TLS certificate. 
	TlsCertificate string `json:"tls_certificate,omitempty"`
	// Set to true to enable use of TLS to secure communication between VAST Cluster and the LDAP server.
	UseTls bool `json:"use_tls,omitempty"`
	// POSIX support
	UsePosix bool `json:"use_posix,omitempty"`
	// A mode setting for how groups are queried: Set to COMPATIBLE to look up user groups using the 'memberOf' and 'memberUid' attributes. Set to RFC2307BIS_ONLY to look up user groups using only the 'memberOf' attribute. Set to RFC2307_ONLY to look up user groups using only the 'memberUid' attribute. Set to NONE not to look up user groups other than by leading GID and primary group SID.
	QueryGroupsMode string `json:"query_groups_mode,omitempty"`
	// The attribute to use for querying users in VMS user-initated user queries. Default is 'name'. Sometimes set to 'cn'
	UsernamePropertyName string `json:"username_property_name,omitempty"`
	// FQDN of AD domain. Must be resolvable in DNS
	DomainName string `json:"domain_name,omitempty"`
	// Specifies the attribute used to query AD for the user login name in NFS ID mapping. Applicable only with AD and NFSv4.1.
	UserLoginName string `json:"user_login_name,omitempty"`
	// Specifies the attribute used to query AD for the group login name in NFS ID mapping. Applicable only with AD and NFSv4.1.
	GroupLoginName string `json:"group_login_name,omitempty"`
	MailPropertyName string `json:"mail_property_name,omitempty"`
	// When enabled, Active Directory Domain Controllers (DCs) and Active Directory domains are auto discovered. Queries extend beyond the joined domain to all domains in the forest. When disabled, queries are restricted to the joined domain and DCs must be provided in the URLs field.
	UseAutoDiscovery bool `json:"use_auto_discovery,omitempty"`
	// Use LDAPS for Auto-Discovery
	UseLdaps bool `json:"use_ldaps,omitempty"`
	// Whether the LDAP should be used for VMS auth. There is only two LDAPs allowed for VMS auth: one with AD and one w/o.
	IsVmsAuthProvider bool `json:"is_vms_auth_provider,omitempty"`
}
