/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DeltaRecord struct {
	Generation int32 `json:"generation"`
	Object *DeltaRecordObject `json:"object"`
	OpType string `json:"op_type"`
	// Arbitrary object in format similar to response from object's uri.
	Data *interface{} `json:"data,omitempty"`
}
