/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AsyncCallhomeConfig struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// Enabled/disabled periodic bundle callhome
	BundleEnabled bool `json:"bundle_enabled,omitempty"`
	// Interval for periodic bundle
	BundleInterval int32 `json:"bundle_interval,omitempty"`
	// Enabled/disabled periodic log callhome
	LogEnabled bool `json:"log_enabled,omitempty"`
	// Interval for periodic log
	LogInterval int32 `json:"log_interval,omitempty"`
	// Customer/Company name
	Customer string `json:"customer,omitempty"`
	// Site name
	Site string `json:"site,omitempty"`
	// Site location
	Location string `json:"location,omitempty"`
	// http, https, socks5, socks5h
	ProxyScheme string `json:"proxy_scheme,omitempty"`
	// Proxy IP/hostname
	ProxyHost string `json:"proxy_host,omitempty"`
	// Proxy Port
	ProxyPort string `json:"proxy_port,omitempty"`
	// Proxy username
	ProxyUsername string `json:"proxy_username,omitempty"`
	// Proxy password
	ProxyPassword string `json:"proxy_password,omitempty"`
	// enable/disable test mode
	TestMode bool `json:"test_mode,omitempty"`
	// Enable/disable ssl certificate verification
	VerifySsl bool `json:"verify_ssl,omitempty"`
	// Enable/disable the vast support channel
	SupportChannel bool `json:"support_channel,omitempty"`
	// Is Cloud reporting modules enabled
	CloudEnabled bool `json:"cloud_enabled,omitempty"`
	// Is the cluster registered with VAST Cloud Services
	CloudRegistered bool `json:"cloud_registered,omitempty"`
	// The API Key for the Cloud API
	CloudApiKey string `json:"cloud_api_key,omitempty"`
	// The domain name for the Cloud API
	CloudApiDomain string `json:"cloud_api_domain,omitempty"`
	// The Customer's subdomain in Vast Cloud Services
	CloudSubdomain string `json:"cloud_subdomain,omitempty"`
	// The id issued to the customer
	CustomerId string `json:"customer_id,omitempty"`
	// Maximum upload concurrency
	MaxUploadConcurrency int32 `json:"max_upload_concurrency,omitempty"`
	// If true, callhome data is obfuscated
	Obfuscated bool `json:"obfuscated,omitempty"`
	// If true, send aggregated callhome logs, otherwise upload logs from each node
	Aggregated bool `json:"aggregated,omitempty"`
	// If true, upload non-aggregated Callhome Bundle via VMS (requires proxy). Otherwise, upload from each node.
	UploadViaVms bool `json:"upload_via_vms,omitempty"`
	// Compression method for callhome bundles (by default zstd)
	CompressMethod string `json:"compress_method,omitempty"`
	// Creation Async task properties
	AsyncTask *interface{} `json:"async_task,omitempty"`
}
