/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Alarm struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Timestamp time.Time `json:"timestamp,omitempty"`
	// Last alarm occurrence
	LastUpdated time.Time `json:"last_updated,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// 
	Cluster string `json:"cluster,omitempty"`
	// 
	ObjectType string `json:"object_type,omitempty"`
	// 
	ObjectId string `json:"object_id,omitempty"`
	// 
	ObjectGuid string `json:"object_guid,omitempty"`
	// 
	Severity string `json:"severity,omitempty"`
	// 
	Event string `json:"event,omitempty"`
	// 
	AlarmMessage string `json:"alarm_message,omitempty"`
	// related event type
	EventType string `json:"event_type,omitempty"`
	// related event definition name
	EventName string `json:"event_name,omitempty"`
	// 
	Metadata *interface{} `json:"metadata,omitempty"`
	// related object's id
	RelObjId string `json:"rel_obj_id,omitempty"`
	// related object's class, possible values: [host, dbox, cbox, null]
	RelObjClass string `json:"rel_obj_class,omitempty"`
}
