/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Monitor struct {
	// 
	Id int32 `json:"id,omitempty"`
	// Monitor name
	Name string `json:"name,omitempty"`
	// Object type
	ObjectType string `json:"object_type,omitempty"`
	// Monitor type (predefined, custom, etc)
	MonitorType string `json:"monitor_type,omitempty"`
	// 
	FromTime time.Time `json:"from_time,omitempty"`
	// 
	ToTime time.Time `json:"to_time,omitempty"`
	// Time frame to use
	TimeFrame string `json:"time_frame,omitempty"`
	// Only query metrics on these objects (optional)
	ObjectIds *interface{} `json:"object_ids,omitempty"`
	// Only query these metrics (optional)
	PropList *interface{} `json:"prop_list,omitempty"`
	// Data granularity
	Granularity string `json:"granularity,omitempty"`
	// Aggregation function. avg, min, max etc.
	Aggregation string `json:"aggregation,omitempty"`
	// Special aggregations to apply on query, e.g intersampling
	QueryAggregation string `json:"query_aggregation,omitempty"`
	// Monitor's metrics exposure
	MetricsExposure string `json:"metrics_exposure,omitempty"`
}
