/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CnodeAddParams struct {
	// The bond internal IP of the new CNode.
	Ip string `json:"ip"`
	// 
	ClusterId int32 `json:"cluster_id,omitempty"`
	// The number of cores the CNode will use
	Cores int32 `json:"cores,omitempty"`
}
