/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Data struct {
	// The Element Store path exposed by the view
	Path string `json:"path"`
	// NFS alias
	Alias string `json:"alias,omitempty"`
}
