/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BigCatalogQueryData struct {
	// Page number
	Page int32 `json:"page,omitempty"`
	// List of column names
	PropList []string `json:"prop_list,omitempty"`
	// List of query data rows
	Data []string `json:"data,omitempty"`
}
