/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type VpnTunnel struct {
	// The tunnel id
	Id int32 `json:"id,omitempty"`
	// The node id on which the tunnel is running
	CnodeId int32 `json:"cnode_id,omitempty"`
	// The host ip adress on which the tunnel is running
	CnodeIp string `json:"cnode_ip,omitempty"`
	// The hostname on which the tunnel is running
	Hostname string `json:"hostname,omitempty"`
	// The addresses of the ip tunnels
	TunnelsIps string `json:"tunnels_ips,omitempty"`
	// The addresses of the ip tunnels
	TunnelEndDate time.Time `json:"tunnel_end_date,omitempty"`
	// The addresses of the ip tunnels
	CreatedAt time.Time `json:"created_at,omitempty"`
}
