/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BigCatalogConfigModifyParams struct {
	// Defines the schedule for snapshot creation and the local and remote retention policies.
	Frames *interface{} `json:"frames,omitempty"`
	// Status of enabling Big Catalog Config
	Enable bool `json:"enable,omitempty"`
}
