/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GroupModifyParams struct {
	// group name
	Name string `json:"name,omitempty"`
	// group GID
	Gid int32 `json:"gid,omitempty"`
	// group SID
	Sid string `json:"sid,omitempty"`
	// list of s3 policy ids
	S3PoliciesIds *interface{} `json:"s3_policies_ids,omitempty"`
}
