/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VpnTunnelCreateParams struct {
	// The ID of one CNode. The tunnel will enable the support engineer to open an SSH session to the specified CNode.
	Cnode int32 `json:"cnode,omitempty"`
	// A username for the VAST-Support tunnel service
	Username string `json:"username,omitempty"`
	// The password for the specified VAST-Support tunnel service user
	Password string `json:"password,omitempty"`
	// The content of a VAST-support VPN configuration file
	VpnConfig string `json:"vpn_config,omitempty"`
	// The duration to allow the tunnel to remain open, in minutes
	Ttl int32 `json:"ttl,omitempty"`
}
