/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type QuotaCreateParams struct {
	// A name for the quota
	Name string `json:"name,omitempty"`
	// The directory path on which to enforce the quota
	Path string `json:"path,omitempty"`
	// Quota enforcement grace period. An alarm is triggered and write operations are blocked if storage usage continues to exceed the soft limit for the grace period. Format: [DD] [HH:[MM:]]ss
	GracePeriod string `json:"grace_period,omitempty"`
	// Storage usage limit at which warnings of exceeding the quota are issued.
	SoftLimit int32 `json:"soft_limit,omitempty"`
	// Storage usage limit beyond which no writes will be allowed.
	HardLimit int32 `json:"hard_limit,omitempty"`
	// Number of directories and unique files under the path beyond which no writes will be allowed. A file with multiple hardlinks is counted only once.
	HardLimitInodes int32 `json:"hard_limit_inodes,omitempty"`
	// Number of directories and unique files under the path at which warnings of exceeding the quota will be issued. A file with multiple hardlinks is counted only once.
	SoftLimitInodes int32 `json:"soft_limit_inodes,omitempty"`
	// Set to true to create the directory if the directory was not created yet.
	CreateDir bool `json:"create_dir,omitempty"`
	DefaultUserQuota *interface{} `json:"default_user_quota,omitempty"`
	DefaultGroupQuota *interface{} `json:"default_group_quota,omitempty"`
	UserQuotas []interface{} `json:"user_quotas,omitempty"`
	GroupQuotas []interface{} `json:"group_quotas,omitempty"`
	EnableAlarms bool `json:"enable_alarms,omitempty"`
	DefaultEmail string `json:"default_email,omitempty"`
	IsUserQuota bool `json:"is_user_quota,omitempty"`
	EnableEmailProviders bool `json:"enable_email_providers,omitempty"`
	// Tenant ID
	TenantId int32 `json:"tenant_id,omitempty"`
}
