/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Ssd struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	InsertionTime time.Time `json:"insertion_time,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// SSD state
	State string `json:"state,omitempty"`
	// SSD enabled
	Enabled bool `json:"enabled,omitempty"`
	// SSD serial number
	Sn string `json:"sn,omitempty"`
	// SSD model
	Model string `json:"model,omitempty"`
	// Total SSD space
	Size int64 `json:"size,omitempty"`
	// Parent Cluster
	Cluster string `json:"cluster,omitempty"`
	// SSD space in use
	SpaceInUse int64 `json:"space_in_use,omitempty"`
	// Parent DBox name
	Dbox string `json:"dbox,omitempty"`
	// The shelf (left/right/front/rear)
	Shelf string `json:"shelf,omitempty"`
	// SSD slot
	Slot int32 `json:"slot,omitempty"`
	// The carrier number ssd resides in
	Carrier int32 `json:"carrier,omitempty"`
	// SSD index in carrier
	IndexInCarrier int32 `json:"index_in_carrier,omitempty"`
	// Attached DNodes
	AttachedDnodeNames string `json:"attached_dnode_names,omitempty"`
	// SSD firmware version
	FwVersion string `json:"fw_version,omitempty"`
	// SSD failure reason
	FailReason string `json:"fail_reason,omitempty"`
	// Carrier hw version
	CarrierHwVersion string `json:"carrier_hw_version,omitempty"`
	// Carrier hw version
	CarrierSwVersion string `json:"carrier_sw_version,omitempty"`
}
