/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserAddParams struct {
	// User name
	Name string `json:"name,omitempty"`
	// NFS UID
	Uid int32 `json:"uid,omitempty"`
	// Leading GID
	LeadingGid int32 `json:"leading_gid,omitempty"`
	// list of GIDs
	Gids []int32 `json:"gids,omitempty"`
	// 
	Local bool `json:"local,omitempty"`
	// Set to true to give the user permission to create S3 buckets
	AllowCreateBucket bool `json:"allow_create_bucket,omitempty"`
	// Set to true to give the user permission to delete S3 buckets
	AllowDeleteBucket bool `json:"allow_delete_bucket,omitempty"`
	// Set to true to give the user S3 superuser permission
	S3Superuser bool `json:"s3_superuser,omitempty"`
	// list of s3 policy ids
	S3PoliciesIds *interface{} `json:"s3_policies_ids,omitempty"`
}
