/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ClusterModifyParams struct {
	// used for cluster rename
	Name string `json:"name,omitempty"`
	// Cluster PSNT
	Psnt string `json:"psnt,omitempty"`
	// Cluster GUID
	Guid string `json:"guid,omitempty"`
	// start/stop cluster
	Enabled bool `json:"enabled,omitempty"`
	// The build to be installed on the cluster
	Build string `json:"build,omitempty"`
	// NFS4 certificate
	Nfs4Certificate string `json:"nfs4_certificate,omitempty"`
	// NFS4 certificate private key
	Nfs4PrivateKey string `json:"nfs4_private_key,omitempty"`
	// S3 HTTPS certificate
	S3Certificate string `json:"s3_certificate,omitempty"`
	// S3 HTTPS certificate private key
	S3PrivateKey string `json:"s3_private_key,omitempty"`
	// Remove S3 certificate pair
	RemoveS3KeyPair bool `json:"remove_s3_key_pair,omitempty"`
	// format cluster
	Format bool `json:"format,omitempty"`
	// Set 30 sec delay in system-status RPC
	SetSystemStatusDelay bool `json:"set_system_status_delay,omitempty"`
	// Clear system status delay
	ClearSystemStatusDelay bool `json:"clear_system_status_delay,omitempty"`
	// Disable dev metrics collection
	DisableMetrics bool `json:"disable_metrics,omitempty"`
	// Should the system collect module level metrics
	DisableModuleMetrics bool `json:"disable_module_metrics,omitempty"`
	// Number of cnode cores
	CnodeCores int32 `json:"cnode_cores,omitempty"`
	// Enables data reduction
	EnableDr bool `json:"enable_dr,omitempty"`
	// Enables data encryption
	EnableEncryption bool `json:"enable_encryption,omitempty"`
	// Enables Similarity
	EnableSimilarity bool `json:"enable_similarity,omitempty"`
	// Auth provider refresh interval (seconds)
	AuthProviderRefreshInterval int32 `json:"auth_provider_refresh_interval,omitempty"`
	// 
	EnableTrash bool `json:"enable_trash,omitempty"`
	// GID with permissions to the trash folder
	TrashGid int32 `json:"trash_gid,omitempty"`
	// 
	MockFanoutAuth bool `json:"mock_fanout_auth,omitempty"`
	// 
	S3AllowCors bool `json:"s3_allow_cors,omitempty"`
	// Allow/deny NFS3 over UDP
	AllowNfs3OverUdp bool `json:"allow_nfs3_over_udp,omitempty"`
	// sw_defined
	SwDefined bool `json:"sw_defined,omitempty"`
	// Inactivity period for auto logout for VAST OS on all nodes (seconds)
	AutoLogoutTimeout int32 `json:"auto_logout_timeout,omitempty"`
	// Custom Message of the Day text displayed by VAST OS on login
	Motd string `json:"motd,omitempty"`
	// Append custom motd to default motd
	MotdAppendToDefault bool `json:"motd_append_to_default,omitempty"`
	// If true, the SMB privileged user is enabled
	UseSmbPrivilegedUser bool `json:"use_smb_privileged_user,omitempty"`
	// Optional custom username for the SMB privileged user. If not set, the SMB privileged user name is 'vastadmin'
	SmbPrivilegedUserName string `json:"smb_privileged_user_name,omitempty"`
	// If true, the SMB privileged group is enabled
	UseSmbPrivilegedGroup bool `json:"use_smb_privileged_group,omitempty"`
	// If true, the SMB privileged group has full access. Otherwise, read only
	SmbPrivilegedGroupFullAccess bool `json:"smb_privileged_group_full_access,omitempty"`
	// Optional custom SID to specify a non default SMB privileged group. If not set, SMB privileged group is the Backup Operators domain group.
	SmbPrivilegedGroupSid string `json:"smb_privileged_group_sid,omitempty"`
	// Optional custom name to specify a non default privileged group. If not set, privileged group is the Backup Operators domain group.
	SmbAdministratorsGroupName string `json:"smb_administrators_group_name,omitempty"`
	// Enable cnode-level metrics collection
	CnodeMetrics bool `json:"cnode_metrics,omitempty"`
	// Enable dbox slots that was disabled by parameter `disable_dboxes_slots`
	RevertDisabledDboxesSlots []ErrorUnknown `json:"revert_disabled_dboxes_slots,omitempty"`
	// True will use used_capacity of Quota and False will use used_effective_capacity
	QuotaFlipCap bool `json:"quota_flip_cap,omitempty"`
	// Enable S3 HTTP
	S3EnableHttp bool `json:"s3_enable_http,omitempty"`
	// Enable S3 HTTPS
	S3EnableHttps bool `json:"s3_enable_https,omitempty"`
	// DBox HA support
	DboxHaSupport bool `json:"dbox_ha_support,omitempty"`
	// Rewrite data
	EnableRewrite bool `json:"enable_rewrite,omitempty"`
	// Efficient Rewrite
	EfficientRewrite bool `json:"efficient_rewrite,omitempty"`
	// Name of the audit directory, which is located under the root directory.
	AuditDirName string `json:"audit_dir_name,omitempty"`
	// Enter users here to grant them read access to all files in the audit directory. To make the audit directory accessible to clients, create a view on the directory.
	ReadAccessUsers []string `json:"read_access_users,omitempty"`
	// Enter groups here to grant them read access to all files in the audit directory. To make the audit directory accessible to clients, create a view on the directory.
	ReadAccessUsersGroups []string `json:"read_access_users_groups,omitempty"`
	// Maximum audit file size for each CNode core
	MaxFileSize int32 `json:"max_file_size,omitempty"`
	// Max retention period for audit files
	MaxRetentionPeriod int32 `json:"max_retention_period,omitempty"`
	// Max retention period timeunit for audit files
	MaxRetentionTimeunit string `json:"max_retention_timeunit,omitempty"`
	// Map of protocols audit configurations
	ProtocolsAudit *interface{} `json:"protocols_audit,omitempty"`
	// Protocols to audit
	Protocols []string `json:"protocols,omitempty"`
	// Enable Turbo Boost
	EnableTurboBoost bool `json:"enable_turbo_boost,omitempty"`
	// Default Share-level permissions for Others
	DefaultOthersShareLevelPerm string `json:"default_others_share_level_perm,omitempty"`
	// mTLS Cluster Certificate
	ClusterCertificate string `json:"cluster_certificate,omitempty"`
	// mTLS Cluster Private Key
	ClusterPrivateKey string `json:"cluster_private_key,omitempty"`
	// mTLS Root Certificate
	RootCertificate string `json:"root_certificate,omitempty"`
}
