/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RequestQosDynamicLimits struct {
	// Maximal amount of performance per GB to provide when there is no resource contention
	MaxReadsBwMbpsPerGbCapacity int32 `json:"max_reads_bw_mbps_per_gb_capacity,omitempty"`
	// Maximal amount of performance per GB to provide when there is no resource contention
	MaxWritesBwMbpsPerGbCapacity int32 `json:"max_writes_bw_mbps_per_gb_capacity,omitempty"`
	// Maximal amount of performance per GB to provide when there is no resource contention
	MaxReadsIopsPerGbCapacity int32 `json:"max_reads_iops_per_gb_capacity,omitempty"`
	// Maximal amount of performance per GB to provide when there is no resource contention
	MaxWritesIopsPerGbCapacity int32 `json:"max_writes_iops_per_gb_capacity,omitempty"`
}
