/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SnapshotpolicyModifyParams struct {
	// Snapshot policy name
	Name string `json:"name,omitempty"`
	// Snapshot expiration time
	SnapshotExpiration string `json:"snapshot_expiration,omitempty"`
	// The maximum number of snapshots that will be retained locally
	MaxCreatedSnapshots int32 `json:"max_created_snapshots,omitempty"`
	// The prefix of the snapshot that will be created
	Prefix string `json:"prefix,omitempty"`
	// The schedule to take the snapshot
	Schedule string `json:"schedule,omitempty"`
	// Enable the policy
	Enabled bool `json:"enabled,omitempty"`
}
