/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelSwitch struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// Switch hostname
	Name string `json:"name,omitempty"`
	// Switch title
	Title string `json:"title,omitempty"`
	// Parent Cluster
	Cluster string `json:"cluster,omitempty"`
	// Switch state
	State string `json:"state,omitempty"`
	// Switch Serial Number
	Sn string `json:"sn,omitempty"`
	// Switch model
	Model string `json:"model,omitempty"`
	// 
	Mtu int32 `json:"mtu,omitempty"`
	// Switch external ip
	Ip string `json:"ip,omitempty"`
	// Switch discovered ipv6
	Ipv6 string `json:"ipv6,omitempty"`
	SwitchType string `json:"switch_type,omitempty"`
}
