/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ShouldUpgrade struct {
	// 
	AllDataExist bool `json:"all_data_exist"`
	// 
	BadPartitions *interface{} `json:"bad_partitions"`
}
