/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type S3PolicyCreateParams struct {
	// S3 policy name
	Name string `json:"name"`
	// JSON policy
	Policy string `json:"policy"`
}
