/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ReplicationRestorePoint struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// guid
	Guid string `json:"guid,omitempty"`
	// state
	State string `json:"state,omitempty"`
	// stream index
	StreamIndex int32 `json:"stream_index,omitempty"`
	// crate id
	CrateId int32 `json:"crate_id,omitempty"`
	// snapshot id
	SnapshotId int32 `json:"snapshot_id,omitempty"`
	// 
	NetworkBwPerSec int64 `json:"network_bw_per_sec,omitempty"`
	// Physical Space
	PhysicalSize int64 `json:"physical_size,omitempty"`
	// Logical Space
	LogicalSize int64 `json:"logical_size,omitempty"`
	// Target name
	TargetName string `json:"target_name,omitempty"`
	// Stream name
	StreamName string `json:"stream_name,omitempty"`
	// 
	Created time.Time `json:"created,omitempty"`
	// Amount of seconds to completion
	EtaSec string `json:"eta_sec,omitempty"`
	// Progress
	ProgressPromil string `json:"progress_promil,omitempty"`
	// 
	Internal bool `json:"internal,omitempty"`
}
