/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Column struct {
	// Name column
	Name string `json:"name,omitempty"`
	// Column type
	Field string `json:"field,omitempty"`
	// Raw description of column type
	RawField string `json:"raw_field,omitempty"`
}
