/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SnapshotCreateParams struct {
	// Snapshot name
	Name string `json:"name"`
	// The path to take a snapshot on
	Path string `json:"path"`
	// Snapshot expiration time
	ExpirationTime string `json:"expiration_time,omitempty"`
	// Cluster ID
	ClusterId int32 `json:"cluster_id,omitempty"`
	// Protect the snapshot from deletion. If locked, a snapshot cannot expire or be deleted without being unlocked first.
	Locked bool `json:"locked,omitempty"`
	// Prevent the snapshot from being deleted
	Indestructible bool `json:"indestructible,omitempty"`
	// Tenant ID
	TenantId int32 `json:"tenant_id,omitempty"`
}
