/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Permission struct {
	// 
	Codename string `json:"codename,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// 
	Realm string `json:"realm,omitempty"`
	// 
	PermissionType string `json:"permission_type,omitempty"`
	// 
	Resources string `json:"resources,omitempty"`
}
