/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ViewCreateParams struct {
	// A name for the view
	Name string `json:"name,omitempty"`
	// The Element Store path to exposed through the view
	Path string `json:"path"`
	// For NFS-enabled views, an alias that can be used by NFSv3 clients
	Alias string `json:"alias,omitempty"`
	// 
	Bucket string `json:"bucket,omitempty"`
	// Specify (by ID) which view policy should be applied to the view
	PolicyId int32 `json:"policy_id,omitempty"`
	// Cluster ID
	ClusterId int32 `json:"cluster_id,omitempty"`
	// Create a directory at the specified path
	CreateDir bool `json:"create_dir,omitempty"`
	// Enabled client access protocols
	Protocols []string `json:"protocols,omitempty"`
	// SMB share name
	Share string `json:"share,omitempty"`
	// S3 Bucket owner
	BucketOwner string `json:"bucket_owner,omitempty"`
	// S3 Object Lock
	S3Locks bool `json:"s3_locks,omitempty"`
	// S3 Locks retention mode
	S3LocksRetentionMode string `json:"s3_locks_retention_mode,omitempty"`
	// Period should be positive in format like 0d|2d|1y|2y
	S3LocksRetentionPeriod string `json:"s3_locks_retention_period,omitempty"`
	BucketCreators []string `json:"bucket_creators,omitempty"`
	BucketCreatorsGroups []string `json:"bucket_creators_groups,omitempty"`
	// S3 Versioning
	S3Versioning bool `json:"s3_versioning,omitempty"`
	// S3 Unverified Lookup
	S3UnverifiedLookup bool `json:"s3_unverified_lookup,omitempty"`
	// Allow S3 anonymous access
	AllowAnonymousAccess bool `json:"allow_anonymous_access,omitempty"`
	// Allow S3 anonymous access
	AllowS3AnonymousAccess bool `json:"allow_s3_anonymous_access,omitempty"`
	// Indicates whether the view should support simultaneous access to NFS3/NFS4/SMB protocols.
	NfsInteropFlags string `json:"nfs_interop_flags,omitempty"`
	// Share-level ACL details
	ShareAcl *interface{} `json:"share_acl,omitempty"`
	SelectForLiveMonitoring bool `json:"select_for_live_monitoring,omitempty"`
	// QoS Policy ID
	QosPolicyId int32 `json:"qos_policy_id,omitempty"`
	// QoS Policy
	QosPolicy string `json:"qos_policy,omitempty"`
	// Tenant ID
	TenantId int32 `json:"tenant_id,omitempty"`
}
