/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VmsSetSslPortParams struct {
	// SSL port number
	SslPort int32 `json:"ssl_port,omitempty"`
}
