/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ActiveDirectory struct {
	//
	Id int32 `json:"id,omitempty"`
	// GUID
	Guid string `json:"guid,omitempty"`
	//
	Name string `json:"name,omitempty"`
	// Name of the computer object/machine account to add. Recommended to be the name of the cluster.
	MachineAccountName string `json:"machine_account_name,omitempty"`
	// Organizational Unit within AD where the Cluster Machine account will be created. If left empty, it will go into default Computers OU
	OrganizationalUnit string `json:"organizational_unit,omitempty"`
	// List of Domain Controllers to prefer for authentication. DCs listed here will be queried exclusively unless they fail or do not respond. In such a case, other DCs will be consulted. Specify as a comma-separated list. Each entry can be a fully-qualified hostname or an IP address.
	PreferredDcList []string `json:"preferred_dc_list,omitempty"`
	// FQDN of the domain.
	DomainName string `json:"domain_name,omitempty"`
	// the id of the attached LDAP object
	LdapId string `json:"ldap_id,omitempty"`
	// enabled/disabled
	Enabled bool `json:"enabled,omitempty"`
	// Active Directory state
	State string `json:"state,omitempty"`
	// Indicates if AD is allowed for SMB. There may only be 1 such AD.
	SmbAllowed bool `json:"smb_allowed,omitempty"`
}
