/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Psu struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// PSU state
	State string `json:"state,omitempty"`
	// PSU serial number
	Sn string `json:"sn,omitempty"`
	// PSU model
	Model string `json:"model,omitempty"`
	// Parent Cluster
	Cluster string `json:"cluster,omitempty"`
	// Parent Box name
	Box string `json:"box,omitempty"`
	// PSU location
	Location string `json:"location,omitempty"`
	// FW version
	FwVersion string `json:"fw_version,omitempty"`
}
