/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VipPool struct {
	//
	Id int32 `json:"id,omitempty"`
	//
	Guid string `json:"guid,omitempty"`
	//
	Name string `json:"name,omitempty"`
	// Starting IP Address of the pool range
	StartIp string `json:"start_ip,omitempty"`
	// Ending IP Address of the pool range
	EndIp string `json:"end_ip,omitempty"`
	// IPv4 Subnet CIDR prefix (bits number)
	SubnetCidr int32 `json:"subnet_cidr,omitempty"`
	// IPv6 Subnet CIDR prefix (bits number)
	SubnetCidrIpv6 int32 `json:"subnet_cidr_ipv6,omitempty"`
	// Gateway IP Address
	GwIp string `json:"gw_ip,omitempty"`
	// GW IPv6 Address
	GwIpv6 string `json:"gw_ipv6,omitempty"`
	// VIPPool VLAN
	Vlan int32 `json:"vlan,omitempty"`
	//
	State string `json:"state,omitempty"`
	// IDs of cnodes comprising cnode group
	CnodeIds []int32 `json:"cnode_ids,omitempty"`
	// Parent Cluster
	Cluster string `json:"cluster,omitempty"`
	// Tenant ID
	TenantId int32 `json:"tenant_id,omitempty"`
	//
	Url string `json:"url,omitempty"`
	//
	DomainName string `json:"domain_name,omitempty"`
	// Role
	Role string `json:"role,omitempty"`
	// Synchronization state with leader
	Sync string `json:"sync,omitempty"`
	// IP ranges
	IpRanges [][]string `json:"ip_ranges,omitempty"`
	// Synchronization time with leader
	SyncTime string `json:"sync_time,omitempty"`
	// If true, CNodes participating in the vip pool are preferred in VMS host election
	VmsPreferred bool `json:"vms_preferred,omitempty"`
	// True for enable, False for disable
	Enabled bool `json:"enabled,omitempty"`
	// The port on the CNode this pool will use. Right, left or all
	PortMembership string `json:"port_membership,omitempty"`
	// Numver of active interfaces
	ActiveInterfaces int32 `json:"active_interfaces,omitempty"`
	// Enables L3 CNode access
	EnableL3 bool `json:"enable_l3,omitempty"`
	// VAST ASN
	VastAsn int32 `json:"vast_asn,omitempty"`
	// Peer ASN
	PeerAsn int32 `json:"peer_asn,omitempty"`
}
