/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ClusterAdvanced struct {
	// Number of shards
	NumberOfShares int32 `json:"number_of_shares,omitempty"`
	// Total cluster capacity in GiB
	TotalCapacityInGib float32 `json:"total_capacity_in_gib,omitempty"`
	// Used cluster capacity in GiB
	UsedCapacityInGib float32 `json:"used_capacity_in_gib,omitempty"`
	// Number of protected shards
	NumberOfProtectedShares int32 `json:"number_of_protected_shares,omitempty"`
	// Number of unprotected shares
	NumberOfUnprotectedShares int32 `json:"number_of_unprotected_shares,omitempty"`
	// Number of files and directories
	NumberOfFilesAndDirectories int32 `json:"number_of_files_and_directories,omitempty"`
	ReadIopsPerSec int32 `json:"read_iops_per_sec,omitempty"`
	ReadLatencyInMillisec float32 `json:"read_latency_in_millisec,omitempty"`
	ReadBandwidthInBytesPerSec int32 `json:"read_bandwidth_in_bytes_per_sec,omitempty"`
	WriteIopsPerSec int32 `json:"write_iops_per_sec,omitempty"`
	WriteLatencyInMillisec float32 `json:"write_latency_in_millisec,omitempty"`
	WriteBandwidthInBytesPerSec int32 `json:"write_bandwidth_in_bytes_per_sec,omitempty"`
}
