/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ExpandParams struct {
	// NVRAM section layout
	NvramSectionLayout string `json:"nvram_section_layout,omitempty"`
	// Devices Mock for NVRAM section layout (only for loopback)
	DevicesMock string `json:"devices_mock,omitempty"`
	// skip layout validation
	SkipLayoutValidation string `json:"skip_layout_validation,omitempty"`
}
