/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DTray struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// 
	Name string `json:"name"`
	// Unique h/w identifier
	Uid string `json:"uid,omitempty"`
	// 
	State string `json:"state,omitempty"`
	// dtray enabled
	Enabled bool `json:"enabled,omitempty"`
	// Parent Cluster
	Cluster string `json:"cluster,omitempty"`
	// DTray Serial Number
	SerialNumber string `json:"serial_number,omitempty"`
	// Parent DBox
	Dbox string `json:"dbox,omitempty"`
	// Position
	Position string `json:"position,omitempty"`
	// BMC FW version
	BmcFwVersion string `json:"bmc_fw_version,omitempty"`
	// PCIE MFG version
	PcieSwitchMfgVersion string `json:"pcie_switch_mfg_version,omitempty"`
	// PCIE switch firmware version
	PcieSwitchFirmwareVersion string `json:"pcie_switch_firmware_version,omitempty"`
	Dnodes []DNode `json:"dnodes,omitempty"`
	// 
	Url string `json:"url,omitempty"`
	// MCU version
	McuVersion string `json:"mcu_version,omitempty"`
	// MCU state
	McuState string `json:"mcu_state,omitempty"`
	// BMC IP
	BmcIp string `json:"bmc_ip,omitempty"`
}
