/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ReplicationPolicy struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// unique identifier
	Guid string `json:"guid,omitempty"`
	// schedule frequency, in datetime format
	ScheduleFrequency time.Time `json:"schedule_frequency,omitempty"`
	// Schedule the first restore point after the initial sync
	ScheduleStartTime time.Time `json:"schedule_start_time,omitempty"`
	// replication target name
	ReplicationTarget string `json:"replication_target,omitempty"`
	// replication target name
	ReplicationTargetName string `json:"replication_target_name,omitempty"`
	// bandwith limitation rules
	BandwidthLimitationRules string `json:"bandwidth_limitation_rules,omitempty"`
	// low / normal / high
	Priority string `json:"priority,omitempty"`
	// ip pool
	VipPool string `json:"vip_pool,omitempty"`
	// Amazon S3 / Amazon Glacier
	AwsPreferredStorage string `json:"aws_preferred_storage,omitempty"`
}
