/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DNode struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// 
	Name string `json:"name"`
	// 
	NewName string `json:"new_name,omitempty"`
	// Currently used IP Address, bond of ip1 and ip2
	Ip string `json:"ip,omitempty"`
	// 1st internal IP Address
	Ip1 string `json:"ip1,omitempty"`
	// 2nd internal IP Address
	Ip2 string `json:"ip2,omitempty"`
	// External IPv6 Address
	Ipv6 string `json:"ipv6,omitempty"`
	// Host label, used to label container, e.g. 11.0.0.1-4000
	HostLabel string `json:"host_label,omitempty"`
	// The host serial number
	Sn string `json:"sn,omitempty"`
	// 
	State string `json:"state,omitempty"`
	// 
	LedStatus string `json:"led_status,omitempty"`
	// dnode enabled
	Enabled bool `json:"enabled,omitempty"`
	// 
	PlatformRdmaPort int32 `json:"platform_rdma_port,omitempty"`
	// 
	PlatformTcpPort int32 `json:"platform_tcp_port,omitempty"`
	// 
	DataRdmaPort int32 `json:"data_rdma_port,omitempty"`
	// 
	DataTcpPort int32 `json:"data_tcp_port,omitempty"`
	// 
	BoxRdmaPort int32 `json:"box_rdma_port,omitempty"`
	// Parent DBox
	Dbox string `json:"dbox,omitempty"`
	// Parent DTray
	Dtray string `json:"dtray,omitempty"`
	// Unique Parent DBox identifier
	DboxUid string `json:"dbox_uid,omitempty"`
	// Parent Cluster
	Cluster string `json:"cluster,omitempty"`
	// Node OS version
	OsVersion string `json:"os_version,omitempty"`
	// BMC FW version
	BmcFwVersion string `json:"bmc_fw_version,omitempty"`
	// 
	Url string `json:"url,omitempty"`
	// 
	Build string `json:"build,omitempty"`
	// Management IP
	MgmtIp string `json:"mgmt_ip,omitempty"`
	// Hostname
	Hostname string `json:"hostname,omitempty"`
	// Synchronization state with leader
	Sync string `json:"sync,omitempty"`
	// Synchronization time with leader
	SyncTime string `json:"sync_time,omitempty"`
	// Indicates if node is primary.
	IsPrimary bool `json:"is_primary,omitempty"`
	// 
	Position string `json:"position,omitempty"`
	// 
	BiosVersion string `json:"bios_version,omitempty"`
}
