/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Indestructibility struct {
	// 
	Id int32 `json:"id,omitempty"`
	// New indestructibility passwd for changing
	NewIndestructibilityPasswd string `json:"new_indestructibility_passwd,omitempty"`
	// First and last name
	Token string `json:"token,omitempty"`
	// First and last name
	TokenTime string `json:"token_time,omitempty"`
	// The password needed to lock/unlock indestructibility in System
	IndestructibilityPasswd string `json:"indestructibility_passwd,omitempty"`
	// The time after which the password will be updated
	PasswdDelay string `json:"passwd_delay,omitempty"`
	// The time when the vms is blocked
	UnlockSystemTime string `json:"unlock_system_time,omitempty"`
	// Indicator of indestructible system
	IsLocked bool `json:"is_locked,omitempty"`
	// The time when VMS restored the password to default settings
	PasswdDelayEta string `json:"passwd_delay_eta,omitempty"`
}
