/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProtectedPathCreateParams struct {
	// 
	Name string `json:"name,omitempty"`
	// path to replicate
	SourceDir string `json:"source_dir,omitempty"`
	// replication policy id
	PolicyId string `json:"policy_id,omitempty"`
	// enable/pause protected path
	Enabled bool `json:"enabled,omitempty"`
	// protection policy id
	ProtectionPolicyId string `json:"protection_policy_id,omitempty"`
	// where to replicate on the remote
	TargetExportedDir string `json:"target_exported_dir,omitempty"`
	// local tenant ID
	TenantId string `json:"tenant_id,omitempty"`
	// remote tenant guid
	RemoteTenantGuid string `json:"remote_tenant_guid,omitempty"`
}
