/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RoleCreateParams struct {
	// Role name
	Name string `json:"name"`
	LdapGroups []ErrorUnknown `json:"ldap_groups,omitempty"`
	// Specify permissions list as an array of permission codenames in the format <permission>-<realm>. To list permission codenames, run /permissions/get.
	PermissionsList string `json:"permissions_list,omitempty"`
}
