/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CarrierModifyParams struct {
	// True for activate, False for deactivate
	Enabled bool `json:"enabled,omitempty"`
}
