/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse2001 struct {
	CountColumns int32 `json:"count_columns,omitempty"`
	CountRows int32 `json:"count_rows,omitempty"`
}
