/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type S3LifeCycleRule struct {
	// 
	Id int32 `json:"id,omitempty"`
	// A unique name
	Name string `json:"name,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// 
	Enabled bool `json:"enabled,omitempty"`
	// The prefix to filter object names
	Prefix string `json:"prefix,omitempty"`
	// The minimum size of the object
	MinSize int32 `json:"min_size,omitempty"`
	// The maximum size of the object
	MaxSize int32 `json:"max_size,omitempty"`
	// The number of days from creation until an object expires
	ExpirationDays int32 `json:"expiration_days,omitempty"`
	// The expiration date of the object
	ExpirationDate string `json:"expiration_date,omitempty"`
	// Remove expired objects delete markers
	ExpiredObjDeleteMarker bool `json:"expired_obj_delete_marker,omitempty"`
	// Number of days after objects become noncurrent
	NoncurrentDays int32 `json:"noncurrent_days,omitempty"`
	// The number of newer versions to retain
	NewerNoncurrentVersions int32 `json:"newer_noncurrent_versions,omitempty"`
	// The number of days until expiration after an incomplete multipart upload
	AbortMpuDaysAfterInitiation int32 `json:"abort_mpu_days_after_initiation,omitempty"`
	// The path of the related View
	ViewPath string `json:"view_path,omitempty"`
	// The ID of the related View
	ViewId int32 `json:"view_id,omitempty"`
}
