/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProtectedPathModifyParams struct {
	// 
	Name string `json:"name,omitempty"`
	// state
	State string `json:"state,omitempty"`
	// path to replicate
	SourceDir string `json:"source_dir,omitempty"`
	// replication policy id
	ReplicationPolicyId string `json:"replication_policy_id,omitempty"`
	// protection policy id
	ProtectionPolicyId string `json:"protection_policy_id,omitempty"`
	// enable/pause protected path
	Enabled bool `json:"enabled,omitempty"`
	// where to replicate on the remote
	TargetExportedDir string `json:"target_exported_dir,omitempty"`
	// Trigger failover command
	Failover bool `json:"failover,omitempty"`
	// abort the failover process
	Abort bool `json:"abort,omitempty"`
	// graceful failover
	Graceful bool `json:"graceful,omitempty"`
}
