/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ReplicationTarget struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// 
	State string `json:"state,omitempty"`
	// unique identifier
	Guid string `json:"guid,omitempty"`
	// A list of canonical urls separated by a comma of the shape: https://user:password@example.com:8080/
	Proxies string `json:"proxies,omitempty"`
	// Authentication secret key
	SecretKey string `json:"secret_key,omitempty"`
	// Authentication access key
	AccessKey string `json:"access_key,omitempty"`
	// Bucket name
	BucketName string `json:"bucket_name,omitempty"`
	// http/https
	HttpProtocol string `json:"http_protocol,omitempty"`
	// Custom bucket url
	CustomBucketUrl string `json:"custom_bucket_url,omitempty"`
	// Amazon only field for region
	AwsRegion string `json:"aws_region,omitempty"`
	// Not yet implemented
	AwsAccountId string `json:"aws_account_id,omitempty"`
	// Not yet implemented
	AwsRole string `json:"aws_role,omitempty"`
}
