/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DnodeModifyParams struct {
	// True for activate, False for deactivate
	Enabled bool `json:"enabled,omitempty"`
	// True for replacement
	Replace bool `json:"replace,omitempty"`
	// True for power off
	PowerOff bool `json:"power_off,omitempty"`
	// True for power on
	PowerOn bool `json:"power_on,omitempty"`
	// If true, skips internal network validation. Allows FRU to proceed if another node is in failed state.
	SkipNetworkValidation bool `json:"skip_network_validation,omitempty"`
}
