/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VmsModifyParams struct {
	// Set to True to disable VMS metrics. Set to False to enable VMS metrics.
	DisableVmsMetrics bool `json:"disable_vms_metrics,omitempty"`
	// VMS Virtual IP
	MgmtVip string `json:"mgmt_vip,omitempty"`
	// The virtual IP on the internal network used for mounting the VMS database.
	MgmtInnerVip string `json:"mgmt_inner_vip,omitempty"`
	// Format capacity properties in base 10 units
	CapacityBase10 bool `json:"capacity_base_10,omitempty"`
	// Format performance properties in base 10 units
	PerformanceBase10 bool `json:"performance_base_10,omitempty"`
	// Minimum supported TLS version (e.g.: 1.2)
	MinTlsVersion string `json:"min_tls_version,omitempty"`
	// Validity duration for JWT access token, specify as [DD [HH:[MM:]]]ss
	AccessTokenLifetime string `json:"access_token_lifetime,omitempty"`
	// Validity duration for JWT refresh token, specify as [DD [HH:[MM:]]]ss
	RefreshTokenLifetime string `json:"refresh_token_lifetime,omitempty"`
	// Custom login banner text for VMS Web UI and CLI
	LoginBanner string `json:"login_banner,omitempty"`
}
