/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TenantCreateParams struct {
	// Tenant name
	Name string `json:"name"`
	// Optional custom username for the SMB privileged user. If not set, the SMB privileged user name is 'vastadmin'
	SmbPrivilegedUserName string `json:"smb_privileged_user_name,omitempty"`
	// Optional custom SID to specify a non default SMB privileged group. If not set, SMB privileged group is the Backup Operators domain group.
	SmbPrivilegedGroupSid string `json:"smb_privileged_group_sid,omitempty"`
	// Optional custom name to specify a non default privileged group. If not set, privileged group is the Backup Operators domain group.
	SmbAdministratorsGroupName string `json:"smb_administrators_group_name,omitempty"`
	// Default Share-level permissions for Others
	DefaultOthersShareLevelPerm string `json:"default_others_share_level_perm,omitempty"`
	// GID with permissions to the trash folder
	TrashGid int32 `json:"trash_gid,omitempty"`
	// Array of source IP ranges to allow for the tenant.
	ClientIpRanges [][]string `json:"client_ip_ranges,omitempty"`
	// POSIX primary provider type
	PosixPrimaryProvider string `json:"posix_primary_provider,omitempty"`
	// AD provider ID
	AdProviderId int32 `json:"ad_provider_id,omitempty"`
	// Open-LDAP provider ID specified separately by the user
	LdapProviderId int32 `json:"ldap_provider_id,omitempty"`
	// NIS provider ID
	NisProviderId int32 `json:"nis_provider_id,omitempty"`
	// Tenant's encryption group unique identifier
	EncryptionCrn string `json:"encryption_crn,omitempty"`
}
