/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Nis struct {
	//
	Id int32 `json:"id,omitempty"`
	//
	Guid string `json:"guid,omitempty"`
	//
	Name string `json:"name,omitempty"`
	//
	DomainName string `json:"domain_name,omitempty"`
	//
	Ips []string `json:"ips,omitempty"`
	//
	Hosts []string `json:"hosts,omitempty"`
	//
	Servers []string `json:"servers,omitempty"`
	// Nis state (CONNECTED/FAILED)
	State string `json:"state,omitempty"`
	// POSIX primary provider
	PosixPrimaryProvider bool `json:"posix_primary_provider,omitempty"`
}
