/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type QosPolicy struct {
	Id int32 `json:"id"`
	// QoS Policy guid
	Guid string `json:"guid"`
	Name string `json:"name"`
	// Allocation of performance resources mode
	Mode string `json:"mode"`
	// Size of a single IO, default is 64K
	IoSizeBytes int32 `json:"io_size_bytes,omitempty"`
	// Static mode limits
	StaticLimits QosStaticLimits `json:"static_limits"`
	// Capacity mode limits
	CapacityLimits QosDynamicLimits `json:"capacity_limits"`
}
