/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DeltaRecordObject struct {
	Type_ string `json:"type"`
	Guid string `json:"guid,omitempty"`
	Id int32 `json:"id"`
}
