/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ColumnDeleteParams struct {
	// Name of the Database
	DatabaseName string `json:"database_name"`
	// Name of the Schema
	SchemaName string `json:"schema_name"`
	// Name of the Table
	TableName string `json:"table_name"`
	// Column description
	ArrowSchema *interface{} `json:"arrow_schema,omitempty"`
}
