/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SnapshotPolicy struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// 
	Name string `json:"name"`
	// Snapshot source path
	Path string `json:"path"`
	// m: minutes, D:days, W:weeks, M:months
	SnapshotExpiration string `json:"snapshot_expiration,omitempty"`
	// The maximum number of snapshots that will be retained locally
	MaxCreatedSnapshots int32 `json:"max_created_snapshots,omitempty"`
	// The state of the last policy operation
	LastOperationState string `json:"last_operation_state,omitempty"`
	// The schedule to take the snapshot
	Schedule string `json:"schedule,omitempty"`
	// Humanize readable schedule
	HumanizeSchedule string `json:"humanize_schedule,omitempty"`
	// The prefix of the snapshot that will be create
	Prefix string `json:"prefix,omitempty"`
	// Parent Cluster
	Cluster string `json:"cluster,omitempty"`
	// Parent Cluster ID
	ClusterId int32 `json:"cluster_id,omitempty"`
	// Parent handle
	Handle string `json:"handle,omitempty"`
	// Enable the policy
	Enabled bool `json:"enabled,omitempty"`
}
