/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GlobalSnapStreamCreateParams struct {
	// Do not specify this parameter.
	Id int32 `json:"id,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// Do not specify this parameter.
	Guid string `json:"guid,omitempty"`
	// Remote target name
	RemoteTarget string `json:"remote_target,omitempty"`
	// Remote target ID
	RemoteTargetId int32 `json:"remote_target_id,omitempty"`
	// Remote snapshot details
	OwnerRootSnapshot *interface{} `json:"owner_root_snapshot,omitempty"`
	// Loanee snapshot name
	LoaneeSnapshot string `json:"loanee_snapshot,omitempty"`
	// Loanee snapshot ID
	LoaneeSnapshotId int32 `json:"loanee_snapshot_id,omitempty"`
	// Loanee path
	LoaneeRootPath string `json:"loanee_root_path,omitempty"`
	// Status
	Status *interface{} `json:"status,omitempty"`
	// Enabled
	Enabled bool `json:"enabled,omitempty"`
}
