/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CallhomeConfigRegisterClusterParams struct {
	// VAST Cloud Services super user login email
	Email string `json:"email,omitempty"`
	// VAST Cloud Services super user password
	Password string `json:"password,omitempty"`
}
