/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GlobalPolicyModifyParams struct {
	// Do not specify this parameter.
	Id int32 `json:"id,omitempty"`
	// Name
	Name string `json:"name"`
	// Do not specify this parameter.
	Guid string `json:"guid,omitempty"`
	// How frequently to send data back to the owner
	ReplicationInterval int32 `json:"replication_interval,omitempty"`
	// Replication interval unit
	ReplicationIntervalUnit string `json:"replication_interval_unit,omitempty"`
	// Lease timeout
	LeaseTimeout int32 `json:"lease_timeout,omitempty"`
	// Lease timeout unit
	LeaseTimeoutUnit string `json:"lease_timeout_unit,omitempty"`
	// Permissions (RO/RW) for all/per auth token
	Permissions *interface{} `json:"permissions,omitempty"`
}
