/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserNonLocalRemoveKeyParams struct {
	// The access key
	AccessKey string `json:"access_key,omitempty"`
	// User UID
	Uid int32 `json:"uid,omitempty"`
	// User SID
	Sid string `json:"sid,omitempty"`
	// Tenant ID
	TenantId int32 `json:"tenant_id,omitempty"`
}
