/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GlobalPathCreateParams struct {
	// Do not specify this parameter.
	Id int32 `json:"id,omitempty"`
	// Do not specify this parameter.
	Guid string `json:"guid,omitempty"`
	// Global Path Name
	Name string `json:"name"`
	// Global Path
	Path string `json:"path,omitempty"`
	// Exposed Path Policy
	Policy string `json:"policy,omitempty"`
	// Exposed Path Policy ID
	PolicyId int32 `json:"policy_id,omitempty"`
	// Global Peer
	Peer string `json:"peer,omitempty"`
	// Global Peer ID
	PeerId int32 `json:"peer_id,omitempty"`
	// Exposed Path
	ExposedPath string `json:"exposed_path,omitempty"`
	// Exposed Path ID
	ExposedPathId int32 `json:"exposed_path_id,omitempty"`
	// Global Path enabled/disabled
	Enabled bool `json:"enabled,omitempty"`
}
