/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Nic struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// NIC name e.g ens785f1
	Name string `json:"name,omitempty"`
	// NIC Port e.g. 1/2
	Port string `json:"port,omitempty"`
	// NIC host
	Host string `json:"host,omitempty"`
	// 
	Address string `json:"address,omitempty"`
	// 
	Ipv6Address string `json:"ipv6_address,omitempty"`
	// Parent Cluster
	Cluster string `json:"cluster,omitempty"`
	// NIC state
	State string `json:"state,omitempty"`
	// NIC Link state
	LinkState string `json:"link_state,omitempty"`
	// 
	Mtu int32 `json:"mtu,omitempty"`
	// FW version
	FwVersion string `json:"fw_version,omitempty"`
}
