/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SwitchCreateParams struct {
	// Switch IP
	Ip string `json:"ip,omitempty"`
	// Switch username
	Username string `json:"username,omitempty"`
	// Switch password
	Password string `json:"password,omitempty"`
}
