/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type AsyncSupportBundle struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// 
	State string `json:"state,omitempty"`
	// The name of the support bundle
	Prefix string `json:"prefix,omitempty"`
	// The path
	Path string `json:"path,omitempty"`
	// 
	BundleFile string `json:"bundle_file,omitempty"`
	// 
	BundleSize string `json:"bundle_size,omitempty"`
	// URL to access/download support bundle file
	BundleUrl string `json:"bundle_url,omitempty"`
	// 
	Level string `json:"level,omitempty"`
	// Start time of logs
	StartTime string `json:"start_time,omitempty"`
	// End time of logs
	EndTime string `json:"end_time,omitempty"`
	// Include only textual logs in bundle
	Text bool `json:"text,omitempty"`
	// Comma separated IDs to fetch (Fetch all if not specified)
	CnodeIds string `json:"cnode_ids,omitempty"`
	// Comma separated IDs to fetch (Fetch all if not specified)
	DnodeIds string `json:"dnode_ids,omitempty"`
	// 
	Created time.Time `json:"created,omitempty"`
	// 
	CreateDatetime string `json:"create_datetime,omitempty"`
	// Aggregate harvests into final bundle
	Aggregated bool `json:"aggregated,omitempty"`
	// A predefined preset bundle
	Preset string `json:"preset,omitempty"`
	// Obfuscate text files
	Obfuscated bool `json:"obfuscated,omitempty"`
	// Parent Cluster
	Cluster string `json:"cluster,omitempty"`
	// 
	Url string `json:"url,omitempty"`
	// Trace files bundle size limit in GB for each node
	MaxSize float32 `json:"max_size,omitempty"`
	// Delete the bundle immediately after successfully uploading
	DeleteAfterSend bool `json:"delete_after_send,omitempty"`
	// Creation Async task properties
	AsyncTask *interface{} `json:"async_task,omitempty"`
}
