/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Vip struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// Virtual IP Address
	Ip string `json:"ip,omitempty"`
	// Parent VIP Pool
	Vippool string `json:"vippool,omitempty"`
	// Parent CNode
	Cnode string `json:"cnode,omitempty"`
	// Parent Cluster
	Cluster string `json:"cluster,omitempty"`
	// 
	Url string `json:"url,omitempty"`
}
