/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CBox struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// 
	Name string `json:"name"`
	// Unique h/w identifier
	Uid string `json:"uid,omitempty"`
	// 
	State string `json:"state,omitempty"`
	// Parent Cluster
	Cluster string `json:"cluster,omitempty"`
	// Description
	Description string `json:"description,omitempty"`
	Cnodes []CNode `json:"cnodes,omitempty"`
	// 
	Url string `json:"url,omitempty"`
}
