/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProtectionPolicyModifyParams struct {
	// Do not specify this parameter.
	Id int32 `json:"id,omitempty"`
	// Name
	Name string `json:"name,omitempty"`
	// Do not specify this parameter.
	Guid string `json:"guid,omitempty"`
	// ID of the remote peer. Specify ID of a ReplicationTarget (aka S3 replication peer) if clone_type is CLOUD_REPLICATION. Specify the ID of a NativeReplicationRemoteTarget if clone_type is NATIVE_REPLICATION.
	TargetObjectId int32 `json:"target_object_id,omitempty"`
	// Defines the schedule for snapshot creation and the local and remote retention policies.
	Frames *interface{} `json:"frames,omitempty"`
	// The prefix for names of snapshots created by the policy
	Prefix string `json:"prefix,omitempty"`
	// Specify the type of data protection. CLOUD_REPLICATION is S3 backup. LOCAL means local snapshots without replication.
	CloneType string `json:"clone_type,omitempty"`
	// Indestructible the Protection policy from being deleted
	Indestructible bool `json:"indestructible,omitempty"`
	// Indicates if Protection Policy will be used for big catalogue. There may only be 1 such policy.
	BigCatalog bool `json:"big_catalog,omitempty"`
}
