/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SnapshotpolicyCreateParams struct {
	// Snapshot policy name
	Name string `json:"name,omitempty"`
	// The source to create the snapshots
	Path string `json:"path,omitempty"`
	// Snapshot expiration time
	SnapshotExpiration string `json:"snapshot_expiration,omitempty"`
	// The maximum number of snapshots that will be retained locally
	MaxCreatedSnapshots int32 `json:"max_created_snapshots,omitempty"`
	// The prefix of the snapshot that will be create
	Prefix string `json:"prefix,omitempty"`
	// The schedule to take the snapshot
	Schedule string `json:"schedule,omitempty"`
	// Cluster ID
	ClusterId int32 `json:"cluster_id,omitempty"`
	// Enable the policy
	Enabled bool `json:"enabled,omitempty"`
}
