/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserNonLocalModifyKeyParams struct {
	// The access key
	AccessKey string `json:"access_key"`
	// Set to true to enable the S3 access key pair. Set to false to disable the S3 access key pair.
	Enabled bool `json:"enabled"`
	// User UID
	Uid int32 `json:"uid"`
	// User SID
	Sid string `json:"sid,omitempty"`
	// Tenant ID
	TenantId int32 `json:"tenant_id,omitempty"`
}
