/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NativeReplicationRemoteTarget struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// Name of remote peer
	PeerName string `json:"peer_name,omitempty"`
	// State of peer connectivity
	State string `json:"state,omitempty"`
	// unique identifier
	Guid string `json:"guid,omitempty"`
	// password for authentication
	Password string `json:"password,omitempty"`
	// A VIP belonging to the remote peer's replication VIP Pool, used for connecting to the remote peer.
	LeadingVip string `json:"leading_vip,omitempty"`
	// VIP range of the remote peer's replication VIP Pool
	RemoteVipRange string `json:"remote_vip_range,omitempty"`
	// The ID of the VIP pool on the local cluster configured with the replication role
	PoolId string `json:"pool_id,omitempty"`
	// The VAST software version running on the local peer.
	Version string `json:"version,omitempty"`
	// The VAST software version running on the remote peer.
	RemoteVersion string `json:"remote_version,omitempty"`
	// The time of the last successful message sent, arrived and acknowledged by the peer.
	LastHeartBeat string `json:"last_heart_beat,omitempty"`
	// The logical capacity remaining available on the remote peer.
	SpaceLeft string `json:"space_left,omitempty"`
	// A certificate to use for authentication with the peer.
	PeerCertificate string `json:"peer_certificate,omitempty"`
	// Not yet implemented
	Secret string `json:"secret,omitempty"`
	// Maximum segment size (MSS), in bytes, that the peer can receive in a single TCP segment.
	Mss int32 `json:"mss,omitempty"`
	// Reflects health of connection between peers.
	Health string `json:"health,omitempty"`
	// Secure mode
	SecureMode string `json:"secure_mode,omitempty"`
}
