/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Group struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Guid string `json:"guid,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// 
	Gid int32 `json:"gid,omitempty"`
	// 
	Sid string `json:"sid,omitempty"`
	// S3 policies IDs
	S3PoliciesIds []int32 `json:"s3_policies_ids,omitempty"`
}
