/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserKeyPair struct {
	// 
	AccessKey string `json:"access_key,omitempty"`
	// 
	SecretKey string `json:"secret_key,omitempty"`
}
