/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ClusterUpgradeParams struct {
	// Specifies the build for upgrade
	Build string `json:"build"`
	// OS upgrade
	OsUpgrade bool `json:"os_upgrade,omitempty"`
	// BMC upgrade
	BmcUpgrade bool `json:"bmc_upgrade,omitempty"`
	// Enables data reduction (DR) for a cluster without DR enabled prior to upgrade
	EnableDr bool `json:"enable_dr,omitempty"`
	// Forces upgrade regardless of version or upgrade state
	Force bool `json:"force,omitempty"`
	// Skips validation of hardware component health. Use with caution since component redundancy is important in NDU. Do not use with OS upgrade.
	SkipHwCheck bool `json:"skip_hw_check,omitempty"`
	// Pull docker images only
	Prepare bool `json:"prepare,omitempty"`
}
