/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserModifyKeyParams struct {
	// The access key to enable
	AccessKey string `json:"access_key"`
	// Set to true to enable access key pair. Set to false to disable access key pair
	Enabled bool `json:"enabled"`
}
