/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GroupQueryModifyParams struct {
	// Group name
	Groupname string `json:"groupname,omitempty"`
	// Group GID
	Gid int32 `json:"gid,omitempty"`
	// Group SID
	Sid string `json:"sid,omitempty"`
	// Group vast ID
	Vaid string `json:"vaid,omitempty"`
	// list of s3 policy ids
	S3PoliciesIds *interface{} `json:"s3_policies_ids,omitempty"`
	// Tenant ID
	TenantId int32 `json:"tenant_id,omitempty"`
}
