/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProtectedPathRestoreParams struct {
	// 
	Name string `json:"name,omitempty"`
	// Id of Snapshot to restore
	LoaneeSnapshotId int32 `json:"loanee_snapshot_id,omitempty"`
}
