/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ReplicationStream struct {
	// 
	Id int32 `json:"id,omitempty"`
	// 
	Name string `json:"name,omitempty"`
	// guid
	Guid string `json:"guid,omitempty"`
	// state
	State string `json:"state,omitempty"`
	// current role in the replication
	Role string `json:"role,omitempty"`
	// path to replicate
	SourceDir string `json:"source_dir,omitempty"`
	// replication policy id
	ReplicationPolicy string `json:"replication_policy,omitempty"`
	// protection policy id
	ProtectionPolicy string `json:"protection_policy,omitempty"`
	// start/pause replication
	Enabled bool `json:"enabled,omitempty"`
	// 
	Internal bool `json:"internal,omitempty"`
}
