/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TokenParams struct {
	// The username for login
	Username string `json:"username,omitempty"`
	// The password for login
	Password string `json:"password,omitempty"`
}
