/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProtectedPathPauseParams struct {
	// Set to False to pause snapshot restore
	Enabled bool `json:"enabled,omitempty"`
}
