/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VmsSetSslCiphersParams struct {
	// SSL Ciphers, e.g. AES256+EECDH:AES256+EDH:!aNULL:!SHA1:!SHA256:!SHA384
	SslCiphers string `json:"ssl_ciphers,omitempty"`
}
