/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ClusterUpgrade struct {
	// Specifies build for upgrade
	Build string `json:"build"`
	// Skips validation of hardware component health. Use with caution since component redundancy is important in NDU. Do not use with OS upgrade.
	SkipHwCheck bool `json:"skip_hw_check,omitempty"`
	// Change system settings from nondr to dr
	EnableDr bool `json:"enable_dr,omitempty"`
	// Pull docker images only
	Prepare bool `json:"prepare,omitempty"`
	// Force upgrade
	Force bool `json:"force,omitempty"`
	// Execute OS upgrade if possible
	Os bool `json:"os,omitempty"`
}
