/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Manager struct {
	// 
	Id int32 `json:"id,omitempty"`
	// The username the user would log in with
	Username string `json:"username,omitempty"`
	// First and last name
	FullName string `json:"full_name,omitempty"`
	// The password needed to log in with
	Password string `json:"password,omitempty"`
	// Retype the password
	PasswordRetype string `json:"password_retype,omitempty"`
	// 
	FirstName string `json:"first_name,omitempty"`
	// 
	LastName string `json:"last_name,omitempty"`
	// The roles
	Roles *interface{} `json:"roles,omitempty"`
	// 
	Permissions *interface{} `json:"permissions,omitempty"`
	// 
	ObjectPermissions *interface{} `json:"object_permissions,omitempty"`
	// Is the manager is a default manager
	IsDefault bool `json:"is_default,omitempty"`
}
