/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserQuota struct {
	// 
	Id int32 `json:"id,omitempty"`
	// Quota guid
	Guid string `json:"guid,omitempty"`
	// The name
	Name string `json:"name,omitempty"`
	State string `json:"state,omitempty"`
	// Quota enforcement grace period in seconds, minutes, hours or days. Example: 90m
	GracePeriod string `json:"grace_period,omitempty"`
	// Grace period expiration time
	TimeToBlock string `json:"time_to_block,omitempty"`
	// Soft quota limit
	SoftLimit int32 `json:"soft_limit,omitempty"`
	// Hard quota limit
	HardLimit int32 `json:"hard_limit,omitempty"`
	// Hard inodes quota limit
	HardLimitInodes int32 `json:"hard_limit_inodes,omitempty"`
	// Soft inodes quota limit
	SoftLimitInodes int32 `json:"soft_limit_inodes,omitempty"`
	// Used inodes
	UsedInodes int32 `json:"used_inodes,omitempty"`
	// Used capacity in bytes
	UsedCapacity int64 `json:"used_capacity,omitempty"`
	// 
	IsAccountable bool `json:"is_accountable,omitempty"`
	// 
	QuotaSystemId int32 `json:"quota_system_id,omitempty"`
	Entity *interface{} `json:"entity,omitempty"`
	EntityIdentifier string `json:"entity_identifier,omitempty"`
}
