/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Injection struct {
	// Injection name
	Name string `json:"name,omitempty"`
	// Injection values
	Values *interface{} `json:"values,omitempty"`
}
