/*
 * VAST Data API
 *
 * A API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GlobalLocalSnapshot struct {
	// The unique ID of the global snapshot.
	Id int64 `json:"id,omitempty"`
	// The unique GUID of the global snapshot.
	Guid string `json:"guid,omitempty"`
	// The name of the snapshot.
	Name string `json:"name,omitempty"`
	// The tenant ID on the destination peer.
	LoaneeTenantId int `json:"loanee_tenant_id,omitempty"`
	// The path where to store the snapshot on the destination peer.
	LoaneeRootPath string `json:"loanee_root_path,omitempty"`
	// The ID of the local snapshot.
	LoaneeSnapshotId int `json:"loanee_snapshot_id,omitempty"`
	// Sets the snapshot to be enabled or disabled.
	Enabled     bool                       `json:"enabled,omitempty"`
	OwnerTenant *GlobalSnapshotOwnerTenant `json:"owner_tenant,omitempty"`
}
