/*
 * VAST Data API
 *
 * A API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type S3LifeCycleRule struct {
	Id int32 `json:"id,omitempty"`
	// A unique name.
	Name    string `json:"name,omitempty"`
	Guid    string `json:"guid,omitempty"`
	Enabled bool   `json:"enabled,omitempty"`
	// Defines a scope of elements (objects, files or directories) by prefix. All objects with keys that begin with the specified prefix are included in the scope. In file and directory nomenclature, a prefix is a file and/or directory path within the view that can include part of the file or directory name. For example, sales/jan would include the file sales/january and the directory sales/jan/week1/. No characters are handled as wildcards.
	Prefix string `json:"prefix,omitempty"`
	// The minimum size of the object.
	MinSize int64 `json:"min_size,omitempty"`
	// The maximum size of the object.
	MaxSize int64 `json:"max_size,omitempty"`
	// The number of days from creation until an object expires.
	ExpirationDays int32 `json:"expiration_days,omitempty"`
	// The expiration date of the object.
	ExpirationDate string `json:"expiration_date,omitempty"`
	// If 'true', removes expired object delete markers.
	ExpiredObjDeleteMarker bool `json:"expired_obj_delete_marker,omitempty"`
	// Number of days after which objects become non-current
	NoncurrentDays int32 `json:"noncurrent_days,omitempty"`
	// The number of newer versions to retain.
	NewerNoncurrentVersions int32 `json:"newer_noncurrent_versions,omitempty"`
	// The number of days until expiration after an incomplete multipart upload.
	AbortMpuDaysAfterInitiation int32 `json:"abort_mpu_days_after_initiation,omitempty"`
	// The path of the view to which the lifecycle rule applies.
	ViewPath string `json:"view_path,omitempty"`
	// The ID of the view to which the lifecycle rule applies.
	ViewId int32 `json:"view_id,omitempty"`
}
