/*
 * VAST Data API
 *
 * A API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type View struct {
	// The unique ID of the view.
	Id int32 `json:"id,omitempty"`
	// The unique GUID of the view.
	Guid string `json:"guid,omitempty"`
	// The unique name of the view.
	Name string `json:"name,omitempty"`
	// File system path. Begin with '/'. Do not include a trailing slash.
	Path string `json:"path"`
	// If true, creates the directory specified by the path.
	CreateDir bool `json:"create_dir,omitempty"`
	// Alias for NFS export. The alias must start with '/' and can include ASCII characters only. If configured, this setting supersedes the exposed NFS export path.
	Alias string `json:"alias,omitempty"`
	// S3 bucket name.
	Bucket string `json:"bucket,omitempty"`
	// The ID of the QoS policy associated with the view.
	PolicyId int32 `json:"policy_id,omitempty"`
	// Parent cluster.
	Cluster string `json:"cluster,omitempty"`
	// Parent cluster ID.
	ClusterId int32 `json:"cluster_id,omitempty"`
	// The ID of the tenant associated with this view.
	TenantId int32 `json:"tenant_id,omitempty"`
	// If true, creates the directory if it does not exist.
	Directory bool `json:"directory,omitempty"`
	// Enables or disables S3 versioning.
	S3Versioning bool `json:"s3_versioning,omitempty"`
	// Allows or prohibits S3 Unverified Lookup.
	S3UnverifiedLookup bool `json:"s3_unverified_lookup,omitempty"`
	// Allow S3 anonymous access
	AllowAnonymousAccess bool `json:"allow_anonymous_access,omitempty"`
	// Allows or prohibits S3 anonymous access.
	AllowS3AnonymousAccess bool `json:"allow_s3_anonymous_access,omitempty"`
	// Protocols exposed by this view.
	Protocols []string `json:"protocols,omitempty"`
	// Name of the SMB share. The name cannot not include the following characters: \" \\ / [ ] : | < > + = ; , * ?
	Share string `json:"share,omitempty"`
	// S3 bucket owner.
	BucketOwner string `json:"bucket_owner,omitempty"`
	// A list of bucket creator users.
	BucketCreators []string `json:"bucket_creators,omitempty"`
	// A list of bucket creator groups.
	BucketCreatorsGroups []string `json:"bucket_creators_groups,omitempty"`
	// Enables or disables S3 object locks.
	S3Locks bool `json:"s3_locks,omitempty"`
	// S3 locks retention mode.
	S3LocksRetentionMode string `json:"s3_locks_retention_mode,omitempty"`
	// Retention period for S3 locks. The period is specified as a positive integer suffixed by a time unit of measure, for example: 0d|2d|1y|2y
	S3LocksRetentionPeriod string `json:"s3_locks_retention_period,omitempty"`
	// Physical capacity.
	PhysicalCapacity int64 `json:"physical_capacity,omitempty"`
	// Logical capacity.
	LogicalCapacity int64 `json:"logical_capacity,omitempty"`
	// Indicates whether the view supports simultaneous access using NFSv3/NFSv4/SMB protocols.
	NfsInteropFlags string        `json:"nfs_interop_flags,omitempty"`
	IsRemote        bool          `json:"is_remote,omitempty"`
	ShareAcl        *ViewShareAcl `json:"share_acl,omitempty"`
	// The ID of the QoS policy associated with the view.
	QosPolicyId int32 `json:"qos_policy_id,omitempty"`
	// Enables or disables support for  seamless failover between replication peers by syncing file handles between the view and remote views on the replicated path on replication peers. This enables NFSv3 client users to retain the same mount point to the view in the event of a failover of the view path to a replication peer. Enabling this option may cause overhead and should only be done when the use case is relevant. To complete the configuration for seamless failover between any two peers, a seamless view must be created on each peer.
	IsSeamless bool `json:"is_seamless,omitempty"`
	// Applicable if locking is enabled. Sets a maximum retention period for files that are locked in the view. Files cannot be locked for longer than this period, whether they are locked manually (by setting the atime) or automatically, using auto-commit. Specify as an integer value followed by a letter for the time unit (m - minutes, h - hours, d - days, y - years). Example: 2y (2 years).
	MaxRetentionPeriod string `json:"max_retention_period,omitempty"`
	// Applicable if locking is enabled. Sets a minimum retention period for files that are locked in the view. Files cannot be locked for less than this period, whether locked manually (by setting the atime) or automatically, using auto-commit. Specify as an integer value followed by a letter for the time unit (h - hours, d - days, m - months, y - years). Example: 1d (1 day).
	MinRetentionPeriod string `json:"min_retention_period,omitempty"`
	// Applicable if locking is enabled. The retention mode for new files. For views enabled for NFSv3 or SMB, if locking is enabled, 'files_retention_mode' must be set to 'GOVERNANCE' or 'COMPLIANCE'. If the view is enabled for S3 and not for NFSv3 or SMB, 'files_retention_mode' can be set to 'NONE'. If set to 'GOVERNANCE', locked files cannot be deleted or changed. The retention period can be shortened or extended by users with sufficient permissions. If set to 'COMPLIANCE', locked files cannot be deleted or changed. The retention period can be extended, but not shortened, by users with sufficient permissions. If set to 'NONE' (S3 only), the retention mode is not set for the view; it is set individually for each object.
	FilesRetentionMode string `json:"files_retention_mode,omitempty"`
	// Relevant if locking is enabled. Required if 's3_locks_retention_mode' is set to 'GOVERNANCE' or 'COMPLIANCE'. Specifies a default retention period for objects in the bucket. If set, object versions that are placed in the bucket are automatically protected with the specified retention lock. Otherwise, by default, each object version has no automatic protection but can be configured with a retention period or legal hold. Specify as an integer followed by h for hours, d for days, m for months, or y for years. For example: 2d or 1y.
	DefaultRetentionPeriod string `json:"default_retention_period,omitempty"`
	// Applicable if locking is enabled. Sets the auto-commit time for files that are locked automatically. These files are locked automatically after the auto-commit period elapses from the time the file is saved. Files locked automatically are locked for the default retention period, after which they are unlocked. Specify as an integer value followed by a letter for the time unit (h - hours, d - days, y - years). Example: 2h (2 hours).
	AutoCommit            string `json:"auto_commit,omitempty"`
	S3ObjectOwnershipRule string `json:"s3_object_ownership_rule,omitempty"`
	// Enables or disables Write Once Read Many (WORM) locking.
	Locking bool `json:"locking,omitempty"`
	// Ignore oos
	IgnoreOos bool `json:"ignore_oos,omitempty"`
	// A list of Attribute-Based Access Control (ABAC) tags. This option can be used only when using SMB/NFSv4 protocols.
	AbacTags []string `json:"abac_tags,omitempty"`
}
