/*
 * VAST Data API
 *
 * A API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NonLocalGroup struct {
	// The ID of the non-local group.
	Id string `json:"id,omitempty"`
	// Group GID.
	Gid int32 `json:"gid,omitempty"`
	// Group SID.
	Sid string `json:"sid,omitempty"`
	// Group name.
	Groupname string `json:"groupname,omitempty"`
	// Tenant ID.
	TenantId int32 `json:"tenant_id,omitempty"`
	// A list of identity policy IDs.
	S3PoliciesIds []int32 `json:"s3_policies_ids,omitempty"`
	// Context from which the user originates. Valid values: 'ad', 'nis' and 'ldap'.
	Context string `json:"context,omitempty"`
}
