/*
 * VAST Data API
 *
 * A API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Nis struct {
	// The unique ID of the NIS server configuration.
	Id int32 `json:"id,omitempty"`
	// The unique GUID of the NIS server configuration.
	Guid string `json:"guid,omitempty"`
	// The NIS server domain name.
	DomainName string `json:"domain_name,omitempty"`
	// A list of IP addresses or hostnames of NIS servers.
	Hosts []string `json:"hosts,omitempty"`
}
