/*
 * VAST Data API
 *
 * A API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Role struct {
	// The unique ID of the role.
	Id int64 `json:"id,omitempty"`
	// The unique name of the role.
	Name string `json:"name,omitempty"`
	// A list of permissions granted.
	PermissionsList []string `json:"permissions_list,omitempty"`
	// A list of granted permissions returned from the VMS.
	Permissions []string `json:"permissions,omitempty"`
	// LDAP group(s) associated with the role. Members of the specified groups on the connected LDAP/Active Directory provider can access VMS and are granted whichever permissions are included in the role. A group can be associated with multiple roles.
	LdapGroups []string `json:"ldap_groups,omitempty"`
	// A list of tenants the role is associated with.
	Tenants []int64 `json:"tenants,omitempty"`
	// If true, the role is an admin role.
	IsAdmin bool `json:"is_admin,omitempty"`
	// If true, the role is a default role.
	IsDefault bool `json:"is_default,omitempty"`
}
