/*
 * VAST Data API
 *
 * A API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserKey struct {
	// The unique ID of the access key.
	Id string `json:"id,omitempty"`
	// The ID of the user to create the key for.
	UserId int32 `json:"user_id,omitempty"`
	// The access key of the user.
	AccessKey string `json:"access_key,omitempty"`
	// The secret key of the user. This secret key is not encrypted and should be kept in an highly secure backend. This field will only be returned if 'pgp_public_key' is not provided.
	SecretKey string `json:"secret_key,omitempty"`
	// The PGP public key in the ASCII armor format to encrypt the secret key returned by the VAST cluster. If this option is set, the 'encrypted_secret_key' will be returned, while 'secret_key' will be empty. Changing this after apply will have no effect.
	PgpPublicKey string `json:"pgp_public_key,omitempty"`
	// The secret key returned from the VAST cluster. This key is encrypted with the public key that was supplied in 'pgp_public_key'.
	EncryptedSecretKey string `json:"encrypted_secret_key,omitempty"`
	// Sets the key to be enabled or disabled.
	Enabled bool `json:"enabled,omitempty"`
}
