/*
 * VAST Data API
 *
 * A API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Snapshot struct {
	// The unique ID of the snapshot.
	Id int64 `json:"id,omitempty"`
	// The unique GUID of the snapshot.
	Guid string `json:"guid,omitempty"`
	// The snapshot's expiration time.
	ExpirationTime string `json:"expiration_time,omitempty"`
	// The name of the snapshot.
	Name string `json:"name,omitempty"`
	// The path to make snapshot from.
	Path string `json:"path,omitempty"`
	// The tenant ID to use.
	TenantId int `json:"tenant_id,omitempty"`
	// If 'true', the snapshot is indestructable.
	Indestructible bool `json:"indestructible,omitempty"`
}
