/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PermissionsPerVipPool struct {
	// The Vippool ID
	VippoolId string `json:"vippool_id,omitempty"`
	// VIP pool permissions 
	VippoolPermissions string `json:"vippool_permissions,omitempty"`
}
