/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NonLocalUser struct {
	// The user unix UID
	Uid int32 `json:"uid,omitempty"`
	// Allow create bucket
	AllowCreateBucket bool `json:"allow_create_bucket,omitempty"`
	// Allow delete bucket
	AllowDeleteBucket bool `json:"allow_delete_bucket,omitempty"`
	// Tenant ID
	TenantId int32 `json:"tenant_id,omitempty"`
	// List S3 policies IDs
	S3PoliciesIds []int32 `json:"s3_policies_ids,omitempty"`
}
