/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NonLocalUserKey struct {
	// The Access key unique identifier
	Id string `json:"id,omitempty"`
	// The user unix UID
	Uid int32 `json:"uid,omitempty"`
	// The access id of the user key
	AccessKey string `json:"access_key,omitempty"`
	// The secret id of the user key
	SecretKey string `json:"secret_key,omitempty"`
	// The PGP public key at ascii armor format to encrypt the secret id returned from vast cluster, if this option is set than the encrypted_secret_key will be returned and secret_key will be empty, changing it after apply will have no affect
	PgpPublicKey string `json:"pgp_public_key,omitempty"`
	// The secret id returned from the vast cluster encrypted with the public key provided at pgp_public_key
	EncryptedSecretKey string `json:"encrypted_secret_key,omitempty"`
	// Tenant ID
	TenantId int32 `json:"tenant_id,omitempty"`
	// Should the key be enabled or disabled
	Enabled bool `json:"enabled,omitempty"`
}
