/*
 * VAST Data API
 *
 * A API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Share-level ACL details.
type ViewShareAcl struct {
	// If true, share-level ACLs are enabled on the view.
	Enabled bool `json:"enabled,omitempty"`
	// Share-level ACL.
	Acl []ShareAcl `json:"acl,omitempty"`
}
