/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GlobalSnapshotOwnerRootSnapshot struct {
	// The ID of the clone
	CloneId int64 `json:"clone_id,omitempty"`
	// Remote Clone Name
	Name string `json:"name,omitempty"`
	// The remote handle (inode)
	ParentHandleEhandle string `json:"parent_handle_ehandle,omitempty"`
}
