/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProtectionPolicySchedule struct {
	// How often to make a snapshot, format is <integer><time period> , while time period can be D - Days ,W - Weeks ,s - Seconds ,m - Minutes, H - Hours, M - Months, Y - Years , Ex 1D = 1 Day
	Every string `json:"every,omitempty"`
	// The start data of the replication
	StartAt string `json:"start-at,omitempty"`
	// For how long to keep a local copy of the replication, format is <integer><time period> , while time period can be D - Days ,W - Weeks ,s - Seconds ,m - Minutes, H - Hours, M - Months, Y - Years , Ex 1D = 1 Day
	KeepLocal string `json:"keep-local,omitempty"`
	// For how long to keep the copy on the remote side, format is <integer><time period> , while time period can be D - Days ,W - Weeks ,s - Seconds ,m - Minutes, H - Hours, M - Months, Y - Years , Ex 1D = 1 Day
	KeepRemote string `json:"keep-remote,omitempty"`
}
