/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProtectionPolicy struct {
	// A unique id given to the replication peer configuration
	Id int64 `json:"id,omitempty"`
	// A unique guid given to the  replication peer configuration
	Guid string `json:"guid,omitempty"`
	// The name of the replication peer configuration
	Name string `json:"name,omitempty"`
	// Direct link to the replication policy
	Url string `json:"url,omitempty"`
	// The target peer name
	TargetName string `json:"target_name,omitempty"`
	// The id of the target peer
	TargetObjectId int `json:"target_object_id,omitempty"`
	// The prefix to be given to the replicated data
	Prefix string `json:"prefix,omitempty"`
	// The type the replication
	CloneType string `json:"clone_type,omitempty"`
	// List of snapshots schedules
	Frames []ProtectionPolicySchedule `json:"frames,omitempty"`
	// Is the snapshot indestructable
	Indestructible bool `json:"indestructible,omitempty"`
}
