/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Share-level ACL details
type ViewShareAcl struct {
	// True if Share ACL is enabled on the view, otherwise False
	Enabled bool `json:"enabled,omitempty"`
	// Share-level ACL
	Acl []ShareAcl `json:"acl,omitempty"`
}
