/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Cnode struct {
	Id      int32  `json:"id,omitempty"`
	Guid    string `json:"guid,omitempty"`
	Name    string `json:"name"`
	NewName string `json:"new_name,omitempty"`
	// The IP address being used, bond of 'ip1' and 'ip2'.
	Ip string `json:"ip,omitempty"`
	// First internal IP address.
	Ip1 string `json:"ip1,omitempty"`
	// Second internal IP address.
	Ip2 string `json:"ip2,omitempty"`
	// External IPv6 address.
	Ipv6 string `json:"ipv6,omitempty"`
	// Host label, used to label the  container, e.g. 11.0.0.1-4000.
	HostLabel string `json:"host_label,omitempty"`
	// Host serial number.
	Sn               string `json:"sn,omitempty"`
	State            string `json:"state,omitempty"`
	DisplayState     string `json:"display_state,omitempty"`
	LedStatus        string `json:"led_status,omitempty"`
	PlatformRdmaPort int32  `json:"platform_rdma_port,omitempty"`
	PlatformTcpPort  int32  `json:"platform_tcp_port,omitempty"`
	DataRdmaPort     int32  `json:"data_rdma_port,omitempty"`
	DataTcpPort      int32  `json:"data_tcp_port,omitempty"`
	// Sets the CNode to be enabled or disabled.
	Enabled bool `json:"enabled,omitempty"`
	// Specifies whether the CNode is running VMS.
	IsMgmt bool `json:"is_mgmt,omitempty"`
	// Parent CBox.
	Cbox string `json:"cbox,omitempty"`
	// UID of the parent CBox.
	CboxUid string `json:"cbox_uid,omitempty"`
	// ID of the parent CBox.
	CboxId int32 `json:"cbox_id,omitempty"`
	// Parent cluster.
	Cluster string `json:"cluster,omitempty"`
	// Node OS version.
	OsVersion string `json:"os_version,omitempty"`
	// BMC FW version.
	BmcFwVersion string `json:"bmc_fw_version,omitempty"`
	// VMS preferred CNode.
	VmsPreferred bool   `json:"vms_preferred,omitempty"`
	Url          string `json:"url,omitempty"`
	// Management IP.
	MgmtIp string `json:"mgmt_ip,omitempty"`
	// Host name.
	Hostname string `json:"hostname,omitempty"`
}
