/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProtectionPolicySchedule struct {
	// How often to create a snapshot. The format is <integer><time period>. The time period can be D - Days, W - Weeks, s - Seconds, m - Minutes, H - Hours, M - Months, Y - Years. For example: 1D = 1 Day
	Every string `json:"every,omitempty"`
	// Replication start date and time.
	StartAt string `json:"start-at,omitempty"`
	// For how long to keep the local copy. The format is <integer><time period>. The time period can be D - Days, W - Weeks, s - Seconds, m - Minutes, H - Hours, M - Months, Y - Years. For example: 1D = 1 Day
	KeepLocal string `json:"keep-local,omitempty"`
	// For how long to keep the copy on the remote peer. The format is <integer><time period>. The time period can be D - Days, W - Weeks, s - Seconds, m - Minutes, H - Hours, M - Months, Y - Years. For example: 1D = 1 Day
	KeepRemote string `json:"keep-remote,omitempty"`
}
