/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Nis struct {
	// A uniq id given to the nis server configuration
	Id int32 `json:"id,omitempty"`
	// A uniq guid given to the nis server configuration
	Guid string `json:"guid,omitempty"`
	// The nis server domain name
	DomainName string `json:"domain_name,omitempty"`
	// List of ip addresses/hostnames of nis servers
	Hosts []string `json:"hosts,omitempty"`
}
