/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type QoSDynamicTotalLimits struct {
	// Maximum bandwidth (in MB/s) per GB to provide when there is no resource contention.
	MaxBwMbpsPerGbCapacity int64 `json:"max_bw_mbps_per_gb_capacity,omitempty"`
	// Maximum IOPS per GB to provide when there is no resource contention.
	MaxIopsPerGbCapacity int64 `json:"max_iops_per_gb_capacity,omitempty"`
}
