/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Realm struct {
	// A unique id given to the realm
	Id int64 `json:"id,omitempty"`
	// A uniqe name of the realm
	Name string `json:"name,omitempty"`
	// List of allowed permissions
	ObjectTypes []string `json:"object_types,omitempty"`
}
