/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProtocolsAudit struct {
	// Audit operations that create or delete files, directories, or objects.
	CreateDeleteFilesDirsObjects bool `json:"create_delete_files_dirs_objects,omitempty"`
	// Log deleted files and directories.
	LogDeletedFilesDirs bool `json:"log_deleted_files_dirs,omitempty"`
	// Log full Element Store path to the requested resource. Enabled by default. May affect performance. When disabled, the view path is recorded.
	LogFullPath bool `json:"log_full_path,omitempty"`
	// Log username of requesting user. Disabled by default
	LogUsername bool `json:"log_username,omitempty"`
	// Log the accessing Hostname
	LogHostname bool `json:"log_hostname,omitempty"`
	// Audit operations that modify data (including operations that change the file size) and metadata
	ModifyDataMd bool `json:"modify_data_md,omitempty"`
	// Audit operations that read data and metadata
	ReadData bool `json:"read_data,omitempty"`
	ModifyData bool `json:"modify_data,omitempty"`
	ReadDataMd bool `json:"read_data_md,omitempty"`
}
