/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type QosUser struct {
	// User FQDN.
	Fqdn  string `json:"fqdn,omitempty"`
	IsSid bool   `json:"is_sid,omitempty"`
	// User SID.
	SidStr   string `json:"sid_str,omitempty"`
	UidOrGid int64  `json:"uid_or_gid,omitempty"`
	// How to display the user.
	Label string `json:"label,omitempty"`
	// User name.
	Value string `json:"value,omitempty"`
	// User login name.
	LoginName string `json:"login_name,omitempty"`
	// User name.
	Name string `json:"name,omitempty"`
	// The type of identifier used to identify the user.
	IdentifierType string `json:"identifier_type,omitempty"`
	// The identifier of type specified in 'identifier_type'.
	IdentifierValue string `json:"identifier_value,omitempty"`
}
