/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type QosStaticLimits struct {
	// Minimum performance to provide when there is resource contention.
	MinReadsBwMbps int64 `json:"min_reads_bw_mbps,omitempty"`
	// Maximum performance to provide when there is no resource contention.
	MaxReadsBwMbps int64 `json:"max_reads_bw_mbps,omitempty"`
	// Minimum performance to provide when there is resource contention.
	MinWritesBwMbps int64 `json:"min_writes_bw_mbps,omitempty"`
	// Maximum performance to provide when there is no resource contention.
	MaxWritesBwMbps int64 `json:"max_writes_bw_mbps,omitempty"`
	// Minimum performance to provide when there is resource contention.
	MinReadsIops int64 `json:"min_reads_iops,omitempty"`
	// Maximum performance to provide when there is no resource contention.
	MaxReadsIops int64 `json:"max_reads_iops,omitempty"`
	// Minimum performance to provide when there is resource contention.
	MinWritesIops int64 `json:"min_writes_iops,omitempty"`
	// Maximum performance to provide when there is no resource contention.
	MaxWritesIops int64 `json:"max_writes_iops,omitempty"`
	// Burst read bandwidth (in MB/s).
	BurstReadsBwMb int64 `json:"burst_reads_bw_mb,omitempty"`
	// Burst read credits (in MB/s).
	BurstReadsLoanMb int64 `json:"burst_reads_loan_mb,omitempty"`
	// Burst write bandwidth (in MB/s).
	BurstWritesBwMb int64 `json:"burst_writes_bw_mb,omitempty"`
	// Burst write credits (in MB/s).
	BurstWritesLoanMb int64 `json:"burst_writes_loan_mb,omitempty"`
	// Burst read IOPS.
	BurstReadsIops int64 `json:"burst_reads_iops,omitempty"`
	// Burst read IOPS credits.
	BurstReadsLoanIops int64 `json:"burst_reads_loan_iops,omitempty"`
	// Burst write IOPS.
	BurstWritesIops int64 `json:"burst_writes_iops,omitempty"`
	// Burst write IOPS credits.
	BurstWritesLoanIops int64 `json:"burst_writes_loan_iops,omitempty"`
}
