/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GlobalSnapshotOwnerTenant struct {
	// The name of the remote tenant.
	Name string `json:"name,omitempty"`
	// The remote tenant GUID.
	Guid string `json:"guid,omitempty"`
}
