/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProtocolsAudit struct {
	// Enables or disables logging of operations that create or delete files, directories, or objects.
	CreateDeleteFilesDirsObjects bool `json:"create_delete_files_dirs_objects,omitempty"`
	// Enables or disables logging of deleted files and directories.
	LogDeletedFilesDirs bool `json:"log_deleted_files_dirs,omitempty"`
	// If 'true' (default), enables logging of full Element Store path to the requested resource. May affect performance. If 'false', the view path is recorded.
	LogFullPath bool `json:"log_full_path,omitempty"`
	// Enables or disables (default) logging of username of the requesting user.
	LogUsername bool `json:"log_username,omitempty"`
	// Enables or disables logging of the accessing host name.
	LogHostname bool `json:"log_hostname,omitempty"`
	// Enables or disables logging of operations that modify metadata.
	ModifyDataMd bool `json:"modify_data_md,omitempty"`
	// Enables or disables logging of operations that read data.
	ReadData   bool `json:"read_data,omitempty"`
	ModifyData bool `json:"modify_data,omitempty"`
	ReadDataMd bool `json:"read_data_md,omitempty"`
}
