/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Snapshot struct {
	// A unique id given to the snapshot
	Id int64 `json:"id,omitempty"`
	// A unique guid given to the snapshot
	Guid string `json:"guid,omitempty"`
	// When will this sanpshot expire
	ExpirationTime string `json:"expiration_time,omitempty"`
	// The name of the snapshot
	Name string `json:"name,omitempty"`
	// The path to make snapshot from
	Path string `json:"path,omitempty"`
	// The tenant id to use
	TenantId int `json:"tenant_id,omitempty"`
	// Is it indestructable
	Indestructible bool `json:"indestructible,omitempty"`
}
