/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Manager struct {
	// The unique ID of the manager.
	Id int64 `json:"id,omitempty"`
	// The unique GUID of the manager.
	Guid string `json:"guid,omitempty"`
	// The username of the manager.
	Username string `json:"username,omitempty"`
	// The password of the manager.
	Password string `json:"password,omitempty"`
	// The manager's first name.
	FirstName string `json:"first_name,omitempty"`
	// The manager's last name.
	LastName string `json:"last_name,omitempty"`
	// A list of permissions granted.
	PermissionsList []string `json:"permissions_list,omitempty"`
	// A list of role IDs.
	Roles []int `json:"roles,omitempty"`
	// If true, the password does not expire.
	PasswordExpirationDisabled bool `json:"password_expiration_disabled,omitempty"`
	// If true, a prompt to replace the password will be displayed next time the user logs in.
	IsTemporaryPassword bool `json:"is_temporary_password,omitempty"`
	// A list of granted permissions returned from the VMS.
	Permissions []string `json:"permissions,omitempty"`
}
