/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NonLocalUser struct {
	// The ID of the non-local user.
	Id string `json:"id,omitempty"`
	// The user's Unix UID.
	Uid int32 `json:"uid,omitempty"`
	// The  username of the non-local user.
	Username string `json:"username,omitempty"`
	// Allows or prohibits bucket creation by the user.
	AllowCreateBucket bool `json:"allow_create_bucket,omitempty"`
	// Allows or prohibits bucket deletion by the user.
	AllowDeleteBucket bool `json:"allow_delete_bucket,omitempty"`
	// Tenant ID.
	TenantId int32 `json:"tenant_id,omitempty"`
	// A list of identity policy IDs.
	S3PoliciesIds []int32 `json:"s3_policies_ids,omitempty"`
	// Context from which the user originates. Valid values: 'ad', 'nis' and 'ldap'.
	Context string `json:"context,omitempty"`
}
