/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Ldap struct {
	Id   int32  `json:"id,omitempty"`
	Guid string `json:"guid,omitempty"`
	// A list of URIs of LDAP servers (Domain Controllers in Active Directory), in priority order. The URI with highest priority that has a good health status is used. Specify each URI in the format '<scheme>://<address>'. '<address>' can be either a DNS name or an IP address, for example: 'ldap://ldap.company.com, ldaps://ldaps.company.com, ldap://192.0.2.2'.
	Urls []string `json:"urls,omitempty"`
	// LDAP server port. 389 (LDAP)  636 (LDAPS)
	Port int32 `json:"port,omitempty"`
	// Distinguished name of the LDAP superuser.
	Binddn string `json:"binddn,omitempty"`
	// Password for the LDAP superuser.
	Bindpw string `json:"bindpw,omitempty"`
	// The base DN is the starting point that the LDAP provider uses when searching for users and groups. If a group base DN is configured, it will be used instead of the base DN, for groups only.
	Searchbase string `json:"searchbase,omitempty"`
	// Base DN for group queries within the joined domain only. When auto-discovery is enabled, group queries outside the joined domain use automatically discovered base DNs.
	GroupSearchbase string `json:"group_searchbase,omitempty"`
	// Bind authentication method.
	Method string `json:"method,omitempty"`
	// Attribute mapping for gid number.
	GidNumber string `json:"gid_number,omitempty"`
	// Attribute mapping for uid.
	Uid string `json:"uid,omitempty"`
	// Attribute mapping for uid number.
	UidNumber string `json:"uid_number,omitempty"`
	// Attribute mapping for user matching.
	MatchUser string `json:"match_user,omitempty"`
	// Attribute mapping for uid member.
	UidMember string `json:"uid_member,omitempty"`
	// Attribute mapping for posix account.
	PosixAccount string `json:"posix_account,omitempty"`
	// Attribute mapping for posix group.
	PosixGroup string `json:"posix_group,omitempty"`
	// Specifies whether to configure LDAP with TLS.
	UseTls bool `json:"use_tls,omitempty"`
	// POSIX primary provider.
	PosixPrimaryProvider  bool   `json:"posix_primary_provider,omitempty"`
	PosixAttributesSource string `json:"posix_attributes_source,omitempty"`
	ReverseLookup         bool   `json:"reverse_lookup,omitempty"`
	TlsCertificate        string `json:"tls_certificate,omitempty"`
	ActiveDirectory       string `json:"active_directory,omitempty"`
	// Query group mode.
	QueryGroupsMode string `json:"query_groups_mode,omitempty"`
	// Username property name.
	UsernamePropertyName string `json:"username_property_name,omitempty"`
	// FQDN of the domain.
	DomainName string `json:"domain_name,omitempty"`
	// The attribute used to query the provider for the user login name in NFS ID mapping.
	UserLoginName string `json:"user_login_name,omitempty"`
	// The attribute used to query the provider for the group login name in NFS ID mapping.
	GroupLoginName             string `json:"group_login_name,omitempty"`
	MailPropertyName           string `json:"mail_property_name,omitempty"`
	UidMemberValuePropertyName string `json:"uid_member_value_property_name,omitempty"`
	// If 'true', Active Directory Domain Controllers (DCs) and Active Directory domains are automatically discovered. Queries extend beyond the joined domain to all domains in the forest. If 'false', queries are restricted to the joined domain and URIs must be provided in 'urls'.
	UseAutoDiscovery bool `json:"use_auto_discovery,omitempty"`
	// Specifies whether to use LDAPS for auto-discovery.
	UseLdaps bool `json:"use_ldaps,omitempty"`
	// Specifies whether the LDAP is to be used for VMS authentication. There can be only two LDAP configurations that can be used for VMS authentication: one with Active Directory and the other without Active Directory.
	IsVmsAuthProvider bool `json:"is_vms_auth_provider,omitempty"`
	// If 'true', users/groups from non-joined domain POSIX attributes are supported. If 'false', POSIX attributes of users/groups from non-joined domain are not supported.
	QueryPosixAttributesFromGc bool `json:"query_posix_attributes_from_gc,omitempty"`
}
