/*
 * VastData API
 *
 * A API document representing VastData API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NonLocalGroup struct {
	// The NonLocalGroup identifier
	Id string `json:"id,omitempty"`
	// Group GID
	Gid int32 `json:"gid,omitempty"`
	// Group SID
	Sid string `json:"sid,omitempty"`
	// Groupname
	Groupname string `json:"groupname,omitempty"`
	// Tenant ID
	TenantId int32 `json:"tenant_id,omitempty"`
	// List S3 policies IDs
	S3PoliciesIds []int32 `json:"s3_policies_ids,omitempty"`
	// Context from which the user originates. Available: 'ad', 'nis' and 'ldap'
	Context string `json:"context,omitempty"`
}
