/*
 * VAST Data API
 *
 * An API document representing VAST Data API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type QosPolicy struct {
	Id int32 `json:"id,omitempty"`
	// QoS policy GUID.
	Guid string `json:"guid,omitempty"`
	Name string `json:"name,omitempty"`
	// QoS provisioning mode.
	Mode string `json:"mode,omitempty"`
	// The QoS policy type.
	PolicyType string `json:"policy_type,omitempty"`
	// Specifies which attributes are setting the limitations.
	LimitBy string `json:"limit_by,omitempty"`
	// When setting 'is_default', this is the tenant for which the policy will be used as the default user QoS policy.
	TenantId int64 `json:"tenant_id,omitempty"`
	// A list of local user IDs to which this QoS policy applies.
	AttachedUsersIdentifiers []string `json:"attached_users_identifiers,omitempty"`
	// Specifies whether this QoS policy is to be used as the default QoS policy per user for this tenant. Setting this attribute requires that 'tenant_id' is also supplied.
	IsDefault bool `json:"is_default,omitempty"`
	// Sets the size of IO for static and capacity limit definitions. The number of IOs per request is obtained by dividing the request size by IO size. Default: 64K. Recommended range: 4K - 1M.
	IoSizeBytes         int64                  `json:"io_size_bytes,omitempty"`
	StaticLimits        *QosStaticLimits       `json:"static_limits,omitempty"`
	CapacityLimits      *QosDynamicLimits      `json:"capacity_limits,omitempty"`
	StaticTotalLimits   *QoSStaticTotalLimits  `json:"static_total_limits,omitempty"`
	CapacityTotalLimits *QoSDynamicTotalLimits `json:"capacity_total_limits,omitempty"`
	AttachedUsers       []QosUser              `json:"attached_users,omitempty"`
}
